import type { Horizon } from './types';

/**
 * Three horizons, ordered by what one person can unblock alone before anything
 * that needs a budget or the whole team. Impact is 1–5 assessed, not forecast —
 * nothing here promises a number the organisation cannot currently measure.
 */
export const ROADMAP: Horizon[] = [
  {
    key: '0-30',
    label: 'Pierwsze 30 dni',
    frame: 'Wyłącznie to, co nowa osoba zrobi sama, bez budżetu i bez zgody zarządu. Cel: przestać zgadywać.',
    items: [
      {
        title: 'Podpiąć analitykę i Search Console',
        why: 'Bez tego cały lejek jest niewidoczny — nie wiadomo, ile osób dociera do formularza ani skąd. Każda dalsza optymalizacja byłaby zgadywaniem.',
        how: 'Poprosić o dostęp do konta Google Analytics i Search Console. Jeśli nie są wpięte — wpiąć. Oznaczyć formularz deklaracji jako zdarzenie konwersji. Dodać parametry UTM do wszystkich linków w postach i newsletterze.',
        owner: 'Marketing',
        effort: 'niski',
        impact: 5,
        metric: 'Widoczna ścieżka od źródła do formularza; liczba wejść na stronę członkostwa tygodniowo',
        funnel: 'pomiar',
        cost: 'zero',
      },
      {
        title: 'Zbramkować raport SME i CEE AI Index',
        why: 'To najmocniejsze aktywa treściowe, jakie mają — badanie na 3 200 respondentach z jedenastu krajów. Jeśli leżą otwarte, budują pozycję, ale nie generują ani jednego kontaktu.',
        how: 'Najpierw ustalić stan faktyczny: czy pobranie wymaga adresu. Jeśli nie — wstawić prosty formularz (imię, firma, rola, e-mail) przed plikiem. Zostawić streszczenie otwarte, żeby nie stracić cytowalności w mediach.',
        owner: 'Marketing',
        effort: 'niski',
        impact: 5,
        metric: 'Liczba pobrań z przechwyconym kontaktem miesięcznie',
        funnel: 'MOFU',
        cost: 'zero',
      },
      {
        title: 'Odwrócić proporcje formatów na LinkedIn',
        why: 'Posty ze zdjęciami ludzi i transmisje biją resztę 3,7-krotnie, a stanowią jedną dziewiątą publikacji. Najczęściej produkowany format — pojedyncza grafika — wypada przedostatnio.',
        how: 'Ustalić minimum: jedna relacja zdjęciowa i jedna transmisja miesięcznie. Fotograf na każdym wydarzeniu, zdjęcia w feedzie tego samego dnia. Ograniczyć pojedyncze grafiki na rzecz karuzel i zdjęć.',
        owner: 'Marketing',
        effort: 'niski',
        impact: 4,
        metric: 'Mediana reakcji na post kwartał do kwartału; udział formatów z ludźmi w publikacjach',
        funnel: 'TOFU',
        cost: 'zero',
      },
      {
        title: 'Spiąć zapisy z webinarów w jedną listę',
        why: 'Cztery webinary w kwartale to cztery pule kontaktów, które prawdopodobnie nigdzie nie trafiają. Transmisje to jedyne miejsce, gdzie toczy się rozmowa — 22 z 48 komentarzy całego kanału.',
        how: 'Sprawdzić, gdzie lądują dane z formularza LinkedIn Events. Eksportować po każdym wydarzeniu do jednej listy. Ustalić właściciela i termin: eksport w ciągu 24 godzin po transmisji.',
        owner: 'Marketing',
        effort: 'niski',
        impact: 4,
        metric: 'Liczba kontaktów pozyskanych z webinarów miesięcznie',
        funnel: 'MOFU',
        cost: 'zero',
      },
      {
        title: 'Rozstrzygnąć los Facebooka',
        why: 'Strona milczy od sierpnia, ma medianę jednej reakcji, zero opinii i przemilczała własny szczyt w Pradze. Jest podlinkowana z witryny, więc pracuje przeciwko sprzedaży członkostwa.',
        how: 'Zamknąć: usunąć link z witryny, zarchiwizować stronę. Albo przypisać właściciela i rytm tygodniowy z treścią pisaną pod platformę. Trzeciej opcji — zostawić jak jest — nie ma.',
        owner: 'Marketing',
        effort: 'niski',
        impact: 3,
        metric: 'Decyzja podjęta i wdrożona; jeśli zostaje — cztery posty miesięcznie',
        funnel: 'TOFU',
        cost: 'zero',
      },
    ],
  },
  {
    key: '30-90',
    label: 'Dni 30–90',
    frame: 'Budowa brakujących elementów lejka. Wymaga pracy i decyzji, nie dużego budżetu. Tu powstaje maszyna.',
    items: [
      {
        title: 'Wyprodukować trzy case studies członków',
        why: 'Między listą logotypów a decyzją o wydatku 1 500 EUR nie ma nic. Dyrektor finansowy nie ma czym uzasadnić kosztu, a to on płaci.',
        how: 'Wybrać trzech członków z różnych segmentów. Jedna strona każdy: jaki mieli problem, co dało członkostwo, jaka liczba się zmieniła. Wersja polska i angielska. Umieścić przy cenniku, nie w zakładce z aktualnościami.',
        owner: 'Marketing + Partnerships',
        effort: 'średni',
        impact: 5,
        metric: 'Współczynnik wypełnień formularza deklaracji przed i po publikacji',
        funnel: 'BOFU',
        cost: '0–1 500 EUR (jeśli zewnętrzny copywriter)',
      },
      {
        title: 'Zbudować sekwencję po webinarze',
        why: 'Zapis na webinar to najcieplejszy sygnał, jaki dostają. Dziś kończy się na powiadomieniu o starcie — kontakt stygnie bez jednego dotknięcia.',
        how: 'Trzy wiadomości: nagranie plus materiały (dzień 1), powiązany raport (dzień 4), zaproszenie do rozmowy o członkostwie z konkretną korzyścią dla segmentu (dzień 10). Jedna sekwencja, nie kampania.',
        owner: 'Marketing',
        effort: 'średni',
        impact: 4,
        metric: 'Odsetek zapisanych, którzy wchodzą na stronę członkostwa',
        funnel: 'MOFU',
        cost: 'koszt narzędzia do wysyłki, rząd 50 EUR/mies.',
      },
      {
        title: 'Uruchomić polskojęzyczną ścieżkę transmisji',
        why: 'Jedyna polska transmisja — o wpływie AI na psychikę — dała 9 komentarzy, drugi wynik w kanale. Postów po polsku są dwa na dwadzieścia siedem, przy bazie członkowskiej z Polski i sześciu wizytach organicznych z polskiego wyszukiwania.',
        how: 'Co druga transmisja po polsku. Tematy z pogranicza technologii i praktyki zarządczej, nie regulacji. Transkrypcja publikowana jako artykuł — to jednocześnie zaczyn odbudowy widoczności w wyszukiwarce.',
        owner: 'Marketing',
        effort: 'średni',
        impact: 4,
        metric: 'Liczba komentarzy i zapisów na transmisje polskie vs angielskie',
        funnel: 'TOFU',
        cost: 'zero',
      },
      {
        title: 'Zamienić karty eksperckie w program',
        why: 'Jedyny format budujący jednocześnie pozycję członka i izby. Użyty czterokrotnie przy około dziewięćdziesięciu firmach członkowskich — zasób na kilkanaście miesięcy leży nietknięty.',
        how: 'Kalendarz: dwie karty miesięcznie, kolejka członków ustalona z góry. Poinformować członków wprost, że to część pakietu — dziś marketing po ich stronie o tym nie wie. Użyć jako argumentu przy pozyskiwaniu kolejnych.',
        owner: 'Marketing + Partnerships',
        effort: 'niski',
        impact: 4,
        metric: 'Liczba kart miesięcznie; liczba członków, którzy udostępnili własną kartę',
        funnel: 'MOFU',
        cost: 'zero',
      },
      {
        title: 'Dodać ścieżkę „porozmawiajmy" obok formularza',
        why: 'Dziś jest „wypełnij i zapłać" albo nic. Firma, która jeszcze nie zdecydowała, nie ma gdzie kliknąć — a przy składce 1 500 EUR większość chce najpierw porozmawiać.',
        how: 'Przycisk rezerwacji rozmowy z kalendarzem obok cennika. Piętnaście minut, jasno opisane: kto dzwoni i o czym. Spięte z tą samą listą co reszta.',
        owner: 'Partnerships',
        effort: 'niski',
        impact: 4,
        metric: 'Liczba umówionych rozmów miesięcznie; odsetek kończących się deklaracją',
        funnel: 'BOFU',
        cost: 'zero (kalendarz w darmowym planie)',
      },
      {
        title: 'Zbudować kalkulator gotowości do AI Act',
        why: 'Izba siedzi w forum doradczym Komisji Europejskiej i ma wiedzę regulacyjną, której nie ma nikt w regionie. Nie zamieniła jej w nic, co przechwytuje kontakt.',
        how: 'Dziesięć pytań, wynik z klasyfikacją ryzyka i listą obowiązków. Raport na e-mail. Dla branż regulowanych to najmocniejszy możliwy magnes — i jedyny, którego konkurencja nie skopiuje bez ich pozycji.',
        owner: 'Marketing + ekspert regulacyjny',
        effort: 'wysoki',
        impact: 5,
        metric: 'Liczba wypełnień miesięcznie; odsetek z segmentu regulowanego',
        funnel: 'MOFU',
        cost: '2 000–5 000 EUR',
      },
    ],
  },
  {
    key: '90-180',
    label: 'Dni 90–180',
    frame: 'Skalowanie tego, co zadziałało, i rzeczy wymagające budżetu albo całego zespołu. Retencja wchodzi na pierwszy plan.',
    items: [
      {
        title: 'Zacząć mierzyć odnowienia',
        why: 'Dla organizacji składkowej to metryka numer jeden i dziś nie istnieje. Bez niej przychód jest zdjęciem, nie modelem, a rozkład członków na pakiety zostaje przedziałem 13,5–135 tys. EUR.',
        how: 'Zestawienie z systemu członkowskiego: kto, jaki pakiet, kiedy wygasa, czy przedłużył. Comiesięczny przegląd wygasających w ciągu 60 dni. To warunek jakiegokolwiek planowania przychodu.',
        owner: 'Operacje + Marketing',
        effort: 'niski',
        impact: 5,
        metric: 'Wskaźnik odnowień; przychód ze składek jako liczba, nie przedział',
        funnel: 'retencja',
        cost: 'zero',
      },
      {
        title: 'Wdrożyć onboarding nowego członka',
        why: 'Pierwsze trzydzieści dni decyduje o odnowieniu. Dziś nie wiadomo, czy cokolwiek się dzieje po zapłaceniu składki.',
        how: 'Sekwencja powitalna: co dostajesz, jak z tego skorzystać, kto jest twoim kontaktem. Rozmowa wdrożeniowa w pierwszym miesiącu. Pierwsza karta ekspercka w pierwszym kwartale — żeby członek od razu zobaczył zwrot.',
        owner: 'Partnerships',
        effort: 'średni',
        impact: 5,
        metric: 'Odsetek nowych członków korzystających z benefitu w pierwszym kwartale',
        funnel: 'retencja',
        cost: 'zero',
      },
      {
        title: 'Zbudować pakiet dla branż regulowanych',
        why: 'Najzamożniejszy segment o najmocniejszym argumencie — AI Act to dla nich koszt i ryzyko, a izba współtworzy przepisy. Dziś płacą tę samą składkę co wszyscy, mimo że wartość dla nich jest wielokrotnie wyższa.',
        how: 'Osobny poziom członkostwa: wczesne ostrzeganie o zmianach regulacyjnych, dostęp do ekspertów, zamknięte spotkania. Wycena oparta na wartości, nie na kosztach. Kalkulator z poprzedniego horyzontu jest wejściem do tego pakietu.',
        owner: 'Zarząd + Partnerships',
        effort: 'wysoki',
        impact: 5,
        metric: 'Liczba członków w nowym pakiecie; średni przychód na członka',
        funnel: 'BOFU',
        cost: 'czas zarządu',
      },
      {
        title: 'Przechwytywać kontakt z wydarzeń partnerskich',
        why: 'GITEX, Vilnius, Carpathian Drone Summit, Master Business Forum — izba jeździ na cudze zasięgi za niewielki koszt i wraca bez listy kontaktów.',
        how: 'Przed każdym wydarzeniem: strona docelowa z materiałem do pobrania i kodem QR na stoisku. Po wydarzeniu: sekwencja w ciągu 48 godzin, póki pamiętają rozmowę.',
        owner: 'Marketing + Partnerships',
        effort: 'średni',
        impact: 4,
        metric: 'Liczba kontaktów na wydarzenie partnerskie',
        funnel: 'TOFU',
        cost: 'zero',
      },
      {
        title: 'Odbudować profil wyszukiwarkowy',
        why: 'Siedem fraz, sześć wizyt miesięcznie, Authority Score 14, a 62,9% anchorów to ogłoszenia handlarzy linkami. Kanał nie istnieje, a odbudowa liczy się w kwartałach.',
        how: 'Plik disavow na szum z poprzedniej analizy. Transkrypcje polskich transmisji jako treść pod realne zapytania. Linki z realnych partnerstw, które już mają — GITEX, Euractiv, The Recursive — zamiast kupowania czegokolwiek.',
        owner: 'Marketing',
        effort: 'średni',
        impact: 3,
        metric: 'Liczba fraz z pozycją w bazie PL; ruch organiczny miesięcznie',
        funnel: 'TOFU',
        cost: 'koszt narzędzia SEO, rząd 100 EUR/mies.',
      },
    ],
  },
];
