import type { DossierPage } from './types';

export const pagePrzeglad: DossierPage = {
  id: 'przeglad',
  num: '01',
  navLabel: "Przegląd",
  group: "Rozpoznanie",
  eyebrow: null,
  title: ``,
  lead: null,
  hero: {
    tag: `Podmiot aktywny · izba gospodarcza · KRS 0001108700`,
    title: `Izba gospodarcza budująca ekosystem AI w <span class="accent">Europie Środkowo-Wschodniej</span>.`,
    lead: `AI Chamber została wpisana do KRS 21 sierpnia 2024 roku<sup class="fn" tabindex="0" role="button" aria-label="Przypis 1 — pokaż źródło" data-refs="1" data-fn="1">1<span class="fc" role="note"><b>1.</b> Krajowy Rejestr Sądowy, wpis podmiotu AI Chamber, KRS 0001108700, NIP 7011219059, REGON 529432945, rejestracja 21 sierpnia 2024 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup>, po publicznej inauguracji marki w kwietniu 2024<sup class="fn" tabindex="0" role="button" aria-label="Przypis 26 — pokaż źródło" data-refs="26" data-fn="2">26<span class="fc" role="note"><b>26.</b> Sifted, materiał o inauguracji AI Chamber, 24 kwietnia 2024 r. - baza startowa blisko 50 firm, deklaracja czterokrotnego wzrostu w ciągu roku, Czechy jako pierwszy cel ekspansji. <em>M2</em></span></sup>. Zrzesza około 90 firm technologicznych z regionu CEE<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="3">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, prowadzi działalność rzeczniczą wobec instytucji krajowych i unijnych<sup class="fn" tabindex="0" role="button" aria-label="Przypis 17, 18 — pokaż źródło" data-refs="17,18" data-fn="4">17,18<span class="fc" role="note"><b>17.</b> AI Chamber wraz z dwunastoma innymi organizacjami regionu, list otwarty w sprawie pakietu Digital Omnibus, grudzień 2025 r. <em>M1</em><br><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup> oraz buduje własny dorobek badawczy<sup class="fn" tabindex="0" role="button" aria-label="Przypis 14, 13 — pokaż źródło" data-refs="14,13" data-fn="5">14,13<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em><br><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em></span></sup>. Rekrutacja na stanowisko Partnerships &amp; Membership Growth Manager dotyczy rdzenia modelu przychodowego organizacji: pozyskiwania członków i partnerów korporacyjnych<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="6">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>.`,
  },
  blocks: [
    { kind: 'html', html: `<div class="metrics c4 block" style="margin-top:34px">
        <div class="metric amber"><div class="n">2024</div><div class="l">rok powstania (KRS 21.08.2024)<sup class="fn" tabindex="0" role="button" aria-label="Przypis 1 — pokaż źródło" data-refs="1" data-fn="7">1<span class="fc" role="note"><b>1.</b> Krajowy Rejestr Sądowy, wpis podmiotu AI Chamber, KRS 0001108700, NIP 7011219059, REGON 529432945, rejestracja 21 sierpnia 2024 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup></div></div>
        <div class="metric"><div class="n">~90</div><div class="l">firm członkowskich na liście publicznej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="8">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup></div></div>
        <div class="metric cyan"><div class="n">4-6<small>%</small></div><div class="l">adopcja AI w CEE<sup class="fn" tabindex="0" role="button" aria-label="Przypis 13 — pokaż źródło" data-refs="13" data-fn="9">13<span class="fc" role="note"><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em></span></sup> wobec 13,5% w Europie Zachodniej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 20 — pokaż źródło" data-refs="20" data-fn="10">20<span class="fc" role="note"><b>20.</b> Eurostat, „Use of artificial intelligence in enterprises”, dane za lata 2024 i 2025 - średnia 13,5%, Polska 8,36% wobec 5,9% w roku poprzednim, Bułgaria 8,55%, Rumunia 5,21%. <em>M2</em></span></sup></div></div>
        <div class="metric"><div class="n">500-800</div><div class="l">członków u odpowiedników z DE i FR<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 23, 24 — pokaż źródło" data-refs="23,24" data-fn="11">23,24<span class="fc" role="note"><b>23.</b> KI Bundesverband, informacja o liczbie członków (ponad 500), ki-verband.de, dostęp: sierpień 2026. <em>M2</em><br><b>24.</b> Hub France IA, informacja o liczbie członków i partnerów (ponad 800, w tym ponad 200 organizacji, ponad 160 startupów i ponad 50 partnerów europejskich), hub-franceia.fr, dostęp: sierpień 2026. <em>M2</em></span></sup></div></div>
      </div>
<div class="verdict block">
        <h4>Teza rozpoznania</h4>
        <p>AI Chamber to organizacja wczesnej fazy z nieproporcjonalnie silnym kapitałem politycznym. Board of Advisors tworzą byli ministrowie i wiceministrowie z Bułgarii, Litwy, Czech i Słowenii<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="12">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>, a wśród członków są ElevenLabs i ICEYE<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="13">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>. Jednocześnie nie ma publicznego cennika składek<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="14">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>, publicznych sprawozdań finansowych ani ujawnionej dynamiki wzrostu bazy członkowskiej. Dla kandydata oznacza to rolę o charakterze zero-do-jednego: budowę powtarzalnego procesu sprzedaży członkostwa niemal od zera, a nie zarządzanie dojrzałą maszyną. Porównanie z odpowiednikami zachodnimi (KI Bundesverband ponad 500 członków<sup class="fn" tabindex="0" role="button" aria-label="Przypis 23 — pokaż źródło" data-refs="23" data-fn="15">23<span class="fc" role="note"><b>23.</b> KI Bundesverband, informacja o liczbie członków (ponad 500), ki-verband.de, dostęp: sierpień 2026. <em>M2</em></span></sup>, Hub France IA ponad 800 członków i partnerów<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 24 — pokaż źródło" data-refs="24" data-fn="16">24<span class="fc" role="note"><b>24.</b> Hub France IA, informacja o liczbie członków i partnerów (ponad 800, w tym ponad 200 organizacji, ponad 160 startupów i ponad 50 partnerów europejskich), hub-franceia.fr, dostęp: sierpień 2026. <em>M2</em></span></sup>) pokazuje skalę dostępnego zapasu wzrostu.</p>
      </div>
<div class="grid3 block">
        <div class="card"><h3 class="mono" style="color:var(--muted);font-size:11px">CO ROZPRACOWAĆ</h3><p style="color:var(--text);margin-top:8px">Organy, ludzie decyzyjni i architektura przychodów - zakładki 02-04.</p></div>
        <div class="card"><h3 class="mono" style="color:var(--muted);font-size:11px">JAK DZIAŁAJĄ</h3><p style="color:var(--text);margin-top:8px">Dorobek badawczy i rzeczniczy, baza członków oraz siedem obszarów działania - zakładki 05-07.</p></div>
        <div class="card"><h3 class="mono" style="color:var(--muted);font-size:11px">POZYCJA RYNKOWA</h3><p style="color:var(--text);margin-top:8px">Konkurencja o tych samych członków i popyt regulacyjny - zakładka 13.</p></div>
      </div>
<p class="note">Dossier zagregowano w sierpniu 2026 roku na podstawie źródeł publicznych. Poziomy wiarygodności oznaczono w zakładce 08. Wszystkie luki informacyjne wskazano wprost zamiast uzupełniać je szacunkami.</p>` },
  ],
};
