import type { DossierPage } from './types';

export const pageStruktura: DossierPage = {
  id: 'struktura',
  num: '02',
  navLabel: "Struktura i organy",
  group: "Rozpoznanie",
  eyebrow: "02 · Struktura i organy",
  title: `Jednoosobowy zarząd, dwa organy kolegialne, podmioty powiązane`,
  lead: `Izbą kieruje jednoosobowy zarząd w osobie Tomasza Snażyka<sup class="fn" tabindex="0" role="button" aria-label="Przypis 1 — pokaż źródło" data-refs="1" data-fn="17">1<span class="fc" role="note"><b>1.</b> Krajowy Rejestr Sądowy, wpis podmiotu AI Chamber, KRS 0001108700, NIP 7011219059, REGON 529432945, rejestracja 21 sierpnia 2024 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup>. Wokół niego zbudowano dwa organy: Board of Directors złożony z przedstawicieli firm członkowskich<sup class="fn" tabindex="0" role="button" aria-label="Przypis 8 — pokaż źródło" data-refs="8" data-fn="18">8<span class="fc" role="note"><b>8.</b> AI Chamber, „Board of Directors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup> oraz Board of Advisors skupiający byłych decydentów rządowych z regionu<sup class="fn" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="19">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>. Diagram pokazuje relacje; karty poniżej zawierają dane rejestrowe.`,
  blocks: [
    { kind: 'component', name: 'structure-graph' },
    { kind: 'html', html: `<div class="grid2 block">
        <div class="card ecard target"><h3>AI Chamber</h3>
          <div class="krs">KRS 0001108700 · podmiot docelowy<sup class="fn" tabindex="0" role="button" aria-label="Przypis 1 — pokaż źródło" data-refs="1" data-fn="20">1<span class="fc" role="note"><b>1.</b> Krajowy Rejestr Sądowy, wpis podmiotu AI Chamber, KRS 0001108700, NIP 7011219059, REGON 529432945, rejestracja 21 sierpnia 2024 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup></div>
          <table><tbody>
            <tr><td>Forma prawna</td><td>Izba gospodarcza</td></tr>
            <tr><td>NIP / REGON</td><td>7011219059 / 529432945</td></tr>
            <tr><td>Rejestracja</td><td class="num tabnum">21.08.2024</td></tr>
            <tr><td>Inauguracja</td><td class="num tabnum">kwiecień 2024 (publiczna)<sup class="fn" tabindex="0" role="button" aria-label="Przypis 26 — pokaż źródło" data-refs="26" data-fn="21">26<span class="fc" role="note"><b>26.</b> Sifted, materiał o inauguracji AI Chamber, 24 kwietnia 2024 r. - baza startowa blisko 50 firm, deklaracja czterokrotnego wzrostu w ciągu roku, Czechy jako pierwszy cel ekspansji. <em>M2</em></span></sup></td></tr>
            <tr><td>Siedziba</td><td>ul. Bolesława Prusa 2,<br>00-493 Warszawa</td></tr>
            <tr><td>Reprezentacja</td><td>zarząd jednoosobowy - prezes reprezentuje izbę samodzielnie</td></tr>
          </tbody></table></div>
        <div class="card ecard engine"><h3>Fundacja AI CEE</h3>
          <div class="krs" style="color:var(--cyan)">KRS 0001064000 · podmiot powiązany<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 2 — pokaż źródło" data-refs="2" data-fn="22">2<span class="fc" role="note"><b>2.</b> Krajowy Rejestr Sądowy, wpis Fundacji AI CEE, KRS 0001064000, rejestracja 17 października 2023 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup></div>
          <table><tbody>
            <tr><td>Rejestracja</td><td class="num tabnum">17.10.2023</td></tr>
            <tr><td>Siedziba</td><td>Warszawa</td></tr>
            <tr><td>Powiązanie</td><td>ten sam założyciel co AI Chamber (Tomasz Snażyk)</td></tr>
            <tr><td>Trzeci podmiot</td><td>Fundacja Startup Poland - Snażyk prezesem od kwietnia 2020<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 32 — pokaż źródło" data-refs="32" data-fn="23">32<span class="fc" role="note"><b>32.</b> „My Company Polska” oraz Wikipedia, biogram Tomasza Snażyka - SKM Legal, Fundacja Startup Poland (prezes od kwietnia 2020), rada nadzorcza Audioteki. <em>M3</em></span></sup></td></tr>
            <tr><td>Znaczenie</td><td>struktura wielopodmiotowa wokół jednej osoby; relacje finansowe między podmiotami nie są jawne</td></tr>
          </tbody></table></div>
      </div>
<div class="card block"><h3>Linia rozwoju <span class="mono">od fundacji do izby</span></h3>
        <div class="tl-item"><div class="tl-year">2023<small>17.10</small></div>
          <div class="tl-body"><h4>Rejestracja Fundacji AI CEE</h4><p>Pierwszy podmiot w strukturze, wpisany do KRS pod numerem 0001064000, z siedzibą w Warszawie<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 2 — pokaż źródło" data-refs="2" data-fn="24">2<span class="fc" role="note"><b>2.</b> Krajowy Rejestr Sądowy, wpis Fundacji AI CEE, KRS 0001064000, rejestracja 17 października 2023 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup>. Poprzedza powstanie izby o dziesięć miesięcy.</p></div></div>
        <div class="tl-item"><div class="tl-year">2024<small>kwiecień</small></div>
          <div class="tl-body"><h4>Publiczna inauguracja marki AI Chamber</h4><p>Ogłoszenie powstania izby w Warszawie z bazą startową liczącą prawie 50 firm<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 26 — pokaż źródło" data-refs="26" data-fn="25">26<span class="fc" role="note"><b>26.</b> Sifted, materiał o inauguracji AI Chamber, 24 kwietnia 2024 r. - baza startowa blisko 50 firm, deklaracja czterokrotnego wzrostu w ciągu roku, Czechy jako pierwszy cel ekspansji. <em>M2</em></span></sup>. W komunikacji założycielskiej pojawia się deklaracja czterokrotnego wzrostu bazy członkowskiej w ciągu roku oraz zapowiedź ekspansji na Czechy<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 26, 28 — pokaż źródło" data-refs="26,28" data-fn="26">26,28<span class="fc" role="note"><b>26.</b> Sifted, materiał o inauguracji AI Chamber, 24 kwietnia 2024 r. - baza startowa blisko 50 firm, deklaracja czterokrotnego wzrostu w ciągu roku, Czechy jako pierwszy cel ekspansji. <em>M2</em><br><b>28.</b> Polska Agencja Prasowa, CRN Polska, „Gazeta Prawna” oraz di.com.pl, komunikaty prasowe o powstaniu i działalności AI Chamber, 2024-2026. <em>M2</em></span></sup>.</p></div></div>
        <div class="tl-item"><div class="tl-year">2024<small>21.08</small></div>
          <div class="tl-body"><h4>Formalny wpis izby gospodarczej do KRS</h4><p>Rejestracja pod numerem 0001108700<sup class="fn" tabindex="0" role="button" aria-label="Przypis 1 — pokaż źródło" data-refs="1" data-fn="27">1<span class="fc" role="note"><b>1.</b> Krajowy Rejestr Sądowy, wpis podmiotu AI Chamber, KRS 0001108700, NIP 7011219059, REGON 529432945, rejestracja 21 sierpnia 2024 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup>. Warto pamiętać o tej rozbieżności: marka działała publicznie od kwietnia<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 26 — pokaż źródło" data-refs="26" data-fn="28">26<span class="fc" role="note"><b>26.</b> Sifted, materiał o inauguracji AI Chamber, 24 kwietnia 2024 r. - baza startowa blisko 50 firm, deklaracja czterokrotnego wzrostu w ciągu roku, Czechy jako pierwszy cel ekspansji. <em>M2</em></span></sup>, forma prawna izby powstała cztery miesiące później.</p></div></div>
        <div class="tl-item"><div class="tl-year">2025<small>lipiec</small></div>
          <div class="tl-body"><h4>Dorobek badawczy i wejście na poziom unijny</h4><p>Publikacja raportu o adopcji AI w MŚP opartego na badaniu ponad 3 200 pracowników z 11 krajów<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 14, 27 — pokaż źródło" data-refs="14,27" data-fn="29">14,27<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em><br><b>27.</b> The Recursive, omówienie raportu AI Chamber o adopcji sztucznej inteligencji w małych i średnich przedsiębiorstwach, 2025 r. <em>M2</em></span></sup> oraz premiera dokumentu w Brukseli we współpracy z NCBR, na styku prezydencji polskiej i duńskiej w Radzie UE<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="30">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>. Uruchomienie CEE AI Action Plan w Gdańsku<sup class="fn" tabindex="0" role="button" aria-label="Przypis 13 — pokaż źródło" data-refs="13" data-fn="31">13<span class="fc" role="note"><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em></span></sup>.</p></div></div>
        <div class="tl-item target"><div class="tl-year">2026<small>wrzesień</small></div>
          <div class="tl-body"><h4>CEE AI Summit w Pradze</h4><p>Flagowa konferencja regionalna zaplanowana na 3 września 2026 roku w Martinic Palace, pod auspicjami czeskiego Ministerstwa Przemysłu i Handlu<sup class="fn" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="32">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>. Baza członkowska na poziomie około 90 firm<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="33">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>.</p></div></div>
      </div>
<div class="card block"><h3>Forma działalności i konsekwencje praktyczne</h3>
        <div class="chips" style="margin-top:12px"><span class="chip">Izba gospodarcza <span class="pill" style="margin-left:6px">forma prawna</span></span><span class="chip">Członkostwo wyłącznie dla MŚP</span><span class="chip">Corporate Partnerships dla dużych firm</span></div>
        <p style="margin-top:14px">Forma izby gospodarczej porządkuje logikę przychodową: podstawą są składki członkowskie<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="34">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>, a duże przedsiębiorstwa obsługiwane są osobną ścieżką partnerską na warunkach indywidualnych<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 11 — pokaż źródło" data-refs="11" data-fn="35">11<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em></span></sup>. Zarząd jednoosobowy oznacza krótką ścieżkę decyzyjną<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 1 — pokaż źródło" data-refs="1" data-fn="36">1<span class="fc" role="note"><b>1.</b> Krajowy Rejestr Sądowy, wpis podmiotu AI Chamber, KRS 0001108700, NIP 7011219059, REGON 529432945, rejestracja 21 sierpnia 2024 r.; odczyt za pośrednictwem rejestr.io, sierpień 2026. <em>M1</em></span></sup>, co przy sprzedaży członkostwa jest przewagą - warunki można domykać szybko.</p>
        <p class="note">Nie ustalono: publicznych sprawozdań finansowych izby, wysokości składek ani relacji finansowych między izbą a Fundacją AI CEE. Te trzy luki warto zaadresować pytaniami na rozmowie (zakładka 12).</p></div>` },
  ],
};
