import type { DossierPage } from './types';

export const pageModel: DossierPage = {
  id: 'model',
  num: '04',
  navLabel: "Model przychodowy",
  group: "Rozpoznanie",
  eyebrow: "04 · Model przychodowy",
  title: `Trzy pakiety MŚP, osobna ścieżka korporacyjna, brak jawnych cen`,
  lead: `Izba nie publikuje sprawozdań finansowych ani cennika składek - wysokość składki widoczna jest dopiero w deklaracji członkowskiej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="51">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>. To sytuacja typowa dla sprzedaży relacyjnej i negocjowanej indywidualnie, ale oznacza, że kandydat wchodzi do procesu bez znajomości poziomów cenowych. Poniżej zrekonstruowana architektura przychodów oraz benchmarki branżowe pozwalające ocenić realność celów.`,
  blocks: [
    { kind: 'component', name: 'members-chart', caption: `Dane z witryn własnych organizacji<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12, 23, 24 — pokaż źródło" data-refs="12,23,24" data-fn="52">12,23,24<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em><br><b>23.</b> KI Bundesverband, informacja o liczbie członków (ponad 500), ki-verband.de, dostęp: sierpień 2026. <em>M2</em><br><b>24.</b> Hub France IA, informacja o liczbie członków i partnerów (ponad 800, w tym ponad 200 organizacji, ponad 160 startupów i ponad 50 partnerów europejskich), hub-franceia.fr, dostęp: sierpień 2026. <em>M2</em></span></sup>. Hub France IA podaje ponad 800 członków i partnerów łącznie (w tym ponad 200 organizacji, ponad 160 startupów i ponad 50 partnerów europejskich), więc porównanie ma charakter poglądowy, a nie liczony według identycznej definicji. Wniosek pozostaje jednak stabilny: rynek dopuszcza bazy członkowskie rzędu setek podmiotów.` },
    { kind: 'html', html: `<div class="metrics c3 block">
        <div class="metric"><div class="n">84<small>%</small></div><div class="l">mediana retencji w organizacjach członkowskich<sup class="fn" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="53">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup></div></div>
        <div class="metric amber"><div class="n">74-75<small>%</small></div><div class="l">retencja pierwszoroczna - najsłabsze ogniwo<sup class="fn" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="54">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup></div></div>
        <div class="metric cyan"><div class="n">52<small>%</small></div><div class="l">nieodnowień z powodu braku zaangażowania, nie ceny<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="55">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup></div></div>
      </div>
<div class="card block"><h3>Pakiety członkowskie<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="56">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup> <span class="mono">wyłącznie dla MŚP</span></h3>
        <table class="data" style="margin-top:10px">
          <thead><tr><th>Pakiet</th><th>Wielkość firmy</th><th>Deklarowany zakres</th></tr></thead>
          <tbody>
            <tr><td>BASIC</td><td>do 5 pracowników</td><td>podstawowy dostęp do wiedzy, społeczność, wspólny głos w advocacy</td></tr>
            <tr><td>PRO</td><td>6-50 pracowników</td><td>większa widoczność, networking, introdukcje biznesowe i inwestorskie</td></tr>
            <tr><td>PREMIUM</td><td>51-250 pracowników</td><td>priorytetowy dostęp, promocja, ekspozycja międzynarodowa, głębsze zaangażowanie w advocacy</td></tr>
            <tr><td>Corporate Partnership</td><td>powyżej 250 pracowników</td><td>współpraca na warunkach indywidualnych, poza standardowym członkostwem</td></tr>
          </tbody>
        </table>
        <div class="matters-title" style="margin-top:14px">Mechanika składki</div>
        <ul class="matters">
          <li>Wysokość składki nie jest publiczna - widoczna dopiero w deklaracji członkowskiej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="57">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>. <span class="v">luka M1</span></li>
          <li>Składka roczna naliczana proporcjonalnie od miesiąca przystąpienia do izby<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="58">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>.</li>
          <li>Obowiązuje jednorazowa opłata rejestracyjna powiększona o VAT<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="59">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>.</li>
          <li>Członkostwo odnawia się automatycznie, jeśli nie zostanie wypowiedziane pisemnie do 31 grudnia<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="60">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>. <span class="v">31.12</span></li>
        </ul>
        <p class="note">Konsekwencja dla roli: automatyczne odnowienie przesuwa ciężar retencji na czwarty kwartał - to naturalny moment kampanii utrzymaniowej i rozmów o wyższy pakiet.</p>
      </div>
<div class="card block"><h3>Corporate Partnerships<sup class="fn" tabindex="0" role="button" aria-label="Przypis 11 — pokaż źródło" data-refs="11" data-fn="61">11<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em></span></sup> <span class="mono">druga ścieżka przychodu</span></h3>
        <p>Członkostwo pozostaje zarezerwowane dla MŚP, natomiast duże przedsiębiorstwa przyjmowane są jako Corporate Partners na zasadach szytych na miarę. Deklarowany pakiet korzyści obejmuje cztery obszary:</p>
        <ul class="matters" style="margin-top:8px">
          <li><b style="color:var(--text)">Strategic Insights</b> - raporty i aktualizacje regulacyjne, w tym dotyczące AI Act.</li>
          <li><b style="color:var(--text)">Premium Connections</b> - roundtables i grupy robocze z udziałem decydentów.</li>
          <li><b style="color:var(--text)">Business Growth</b> - szkolenia i programy rozwojowe.</li>
          <li><b style="color:var(--text)">Market Visibility</b> - certyfikacja partnerska i digital badging.</li>
        </ul>
        <p class="note">Kontakt w sprawie partnerstw korporacyjnych prowadzi bezpośrednio Agnieszka Gosztyła<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 11, 31 — pokaż źródło" data-refs="11,31" data-fn="62">11,31<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em><br><b>31.</b> Profile zawodowe w serwisie LinkedIn: Tomasz Snażyk, Agnieszka Gosztyła, Marcin Olender, Monika Kalkusová, Paulina Król oraz członkowie Board of Directors i Board of Advisors; odczyt: sierpień 2026. <em>M3</em></span></sup>, co potwierdza, że to ona odpowiada za obszar objęty rekrutacją<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="63">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>.</p>
      </div>
<div class="card block"><h3>Zrekonstruowana architektura przychodów<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10, 11, 18 — pokaż źródło" data-refs="10,11,18" data-fn="64">10,11,18<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em><br><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em><br><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup></h3>
        <table class="data" style="margin-top:10px">
          <thead><tr><th>Strumień</th><th>Charakter</th><th>Status wiedzy</th></tr></thead>
          <tbody>
            <tr><td>Składki członkowskie MŚP</td><td>powtarzalny, subskrypcyjny, trzy poziomy</td><td><span class="pill warn">ceny niejawne</span></td></tr>
            <tr><td>Corporate Partnerships</td><td>kontrakty indywidualne, wyższa wartość jednostkowa</td><td><span class="pill warn">ceny niejawne</span></td></tr>
            <tr><td>Sponsoring wydarzeń</td><td>projektowy, powiązany z CEE AI Summit i formatami mniejszymi</td><td><span class="pill cyan">potwierdzony jakościowo</span></td></tr>
            <tr><td>Projekty badawcze z partnerami publicznymi</td><td>współpraca m.in. z NCBR przy raporcie o MŚP<sup class="fn" tabindex="0" role="button" aria-label="Przypis 14, 18 — pokaż źródło" data-refs="14,18" data-fn="65">14,18<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em><br><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup></td><td><span class="pill cyan">potwierdzony jakościowo</span></td></tr>
            <tr><td>Opłata rejestracyjna</td><td>jednorazowa, przy przystąpieniu</td><td><span class="pill pos">potwierdzona</span></td></tr>
          </tbody>
        </table>
      </div>
<div class="verdict cyan block"><h4>Wniosek dla stanowiska</h4><p>Rola obejmuje oba strumienie o najwyższej dźwigni: powtarzalne składki MŚP oraz wysokojednostkowe partnerstwa korporacyjne. Przy około 90 członkach i braku publicznego cennika największym ryzykiem nie jest brak popytu, lecz brak ustandaryzowanego procesu - długość cyklu i konwersja zależą wtedy od pojedynczych rozmów. Benchmarki branżowe wskazują, gdzie leży realny zysk: przy medianie retencji 84% i retencji pierwszorocznej na poziomie 74-75%<sup class="fn" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="66">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup>, każdy pozyskany członek, który nie przetrwa pierwszego roku, kasuje wynik akwizycji. Ponieważ 52% nieodnowień wynika z braku zaangażowania, a nie z ceny<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="67">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup>, program onboardingu jest tańszym źródłem wzrostu netto niż zwiększanie liczby nowych rozmów.</p></div>
<p class="note">Nie ustalono: przychodów izby, wysokości składek, liczby partnerów korporacyjnych ani dynamiki bazy członkowskiej miesiąc do miesiąca. Benchmarki retencji pochodzą z raportu Marketing General Incorporated dotyczącego organizacji członkowskich (poziom M2)<sup class="fn p" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="68">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup> i opisują rynek amerykański - w warunkach CEE należy je traktować jako punkt odniesienia, nie jako cel.</p>` },
  ],
};
