import type { DossierPage } from './types';

export const pageDorobek: DossierPage = {
  id: 'dorobek',
  num: '05',
  navLabel: "Dorobek / case studies",
  group: "Działalność i pozycja",
  eyebrow: "05 · Dorobek badawczy i rzeczniczy",
  title: `Dorobek / case studies`,
  lead: `Sześć publicznie udokumentowanych projektów izby z lat 2024-2026<sup class="fn" tabindex="0" role="button" aria-label="Przypis 13, 14, 16, 17, 18 — pokaż źródło" data-refs="13,14,16,17,18" data-fn="69">13,14,16,17,18<span class="fc" role="note"><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em><br><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em><br><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em><br><b>17.</b> AI Chamber wraz z dwunastoma innymi organizacjami regionu, list otwarty w sprawie pakietu Digital Omnibus, grudzień 2025 r. <em>M1</em><br><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>. Każda karta pokazuje charakter przedsięwzięcia, rolę AI Chamber oraz rezultat. To materiał do bezpośredniego wykorzystania w rozmowie: dowody wartości, które można pokazać potencjalnemu członkowi.`,
  blocks: [
    {
      kind: 'tabs',
      group: 'cs',
      tabs: [
        { id: 'cs-1', label: "Raport MŚP", html: `
          <div class="cs-hero"><span class="client"><span class="sq"></span>Badania · 11 krajów CEE</span>
            <h3>Badanie adopcji AI w MŚP na próbie ponad 3 200 pracowników</h3>
            <p>Raport „How do SMEs in CEE find their way in the world of AI?” opublikowany w lipcu 2025 roku<sup class="fn" tabindex="0" role="button" aria-label="Przypis 14 — pokaż źródło" data-refs="14" data-fn="70">14<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em></span></sup> to najmocniejsza pozycja badawcza izby. Objął ponad 3 200 pracowników z 11 krajów regionu<sup class="fn" tabindex="0" role="button" aria-label="Przypis 14, 27 — pokaż źródło" data-refs="14,27" data-fn="71">14,27<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em><br><b>27.</b> The Recursive, omówienie raportu AI Chamber o adopcji sztucznej inteligencji w małych i średnich przedsiębiorstwach, 2025 r. <em>M2</em></span></sup> i dał organizacji własne dane pierwotne, a nie tylko komentarz do cudzych analiz.</p>
            <div class="scope"><span class="pill">3 200+ respondentów</span><span class="pill">11 krajów</span><span class="pill">dane pierwotne</span></div></div>
          <div class="steps">
            <div class="step"><div class="lbl">Problem</div><h4>Brak danych o realnej adopcji AI w regionie</h4><p>Debata o AI w CEE opierała się na danych zagregowanych dla całej Unii, które maskowały dystans regionu do Europy Zachodniej.</p></div>
            <div class="step"><div class="lbl">Rola AI Chamber</div><h4>Projekt i realizacja badania regionalnego</h4><p>Przeprowadzenie badania w 11 krajach i opracowanie raportu, poprzedzone pierwszą publikacją „Raport AI Chamber 2024 - Rola AI w MŚP” z września 2024 roku<sup class="fn" tabindex="0" role="button" aria-label="Przypis 15 — pokaż źródło" data-refs="15" data-fn="72">15<span class="fc" role="note"><b>15.</b> AI Chamber, „Raport AI Chamber 2024. Rola AI w MŚP”, wrzesień 2024 r. <em>M1</em></span></sup>.</p></div>
            <div class="step"><div class="lbl">Rezultat</div><h4>Własna baza dowodowa i pozycja ekspercka</h4><p>Raport stał się podstawą narracji o luce adopcyjnej i punktem odniesienia w rozmowach z instytucjami. Dał izbie coś, czego nie da się kupić szybko: własne liczby.</p></div>
          </div>
          <div class="relnote"><b>Znaczenie dla stanowiska</b>To najskuteczniejsze narzędzie akwizycyjne w portfelu izby. Rozmowa z potencjalnym członkiem nie musi zaczynać się od zapewnień o wartości członkostwa, tylko od danych pokazujących, gdzie stoi jego rynek i dlaczego to problem właśnie teraz.</div>
        ` },
        { id: 'cs-2', label: "CEE AI Action Plan", html: `
          <div class="cs-hero"><span class="client"><span class="sq"></span>Policy · prezydencja polska w Radzie UE</span>
            <h3>CEE AI Action Plan - pięciofilarowy program dla regionu</h3>
            <p>Dokument uruchomiony w Gdańsku podczas polskiej prezydencji w Radzie UE w 2025 roku<sup class="fn r n" tabindex="0" role="button" aria-label="Przypis 13 — pokaż źródło" data-refs="13" data-fn="73">13<span class="fc" role="note"><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em></span></sup>. Formułuje program rozwoju AI dla całego regionu w pięciu filarach<sup class="fn" tabindex="0" role="button" aria-label="Przypis 13 — pokaż źródło" data-refs="13" data-fn="74">13<span class="fc" role="note"><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em></span></sup> i jednocześnie pozycjonuje izbę jako podmiot mówiący w imieniu CEE, a nie tylko Polski.</p>
            <div class="scope"><span class="pill">5 filarów</span><span class="pill">prezydencja PL</span><span class="pill">poziom regionalny</span></div></div>
          <div class="steps">
            <div class="step"><div class="lbl">Zakres</div><h4>Pięć filarów programu</h4>
              <ul><li>Infrastruktura - regionalna sieć obliczeniowa HPC</li><li>Dane - dostępność i jakość zasobów danych</li><li>Kapitał ludzki - kompetencje i talenty</li><li>Regulacje - przewidywalne otoczenie prawne</li><li>Finansowanie - dostęp do kapitału, w szczególności późnej fazy</li></ul></div>
            <div class="step"><div class="lbl">Rola AI Chamber</div><h4>Autorstwo i uruchomienie dokumentu</h4><p>Wykorzystanie okna politycznego polskiej prezydencji do premiery programu obejmującego cały region, z danymi o luce adopcyjnej jako uzasadnieniem.</p></div>
            <div class="step"><div class="lbl">Rezultat</div><h4>Pozycja rzecznika regionu</h4><p>Uzupełnieniem stała się promocja wspólnego bidu CEE na AI Gigafactory, łączącego Polskę, kraje bałtyckie i Czechy<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="75">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup> - konkretny projekt zamiast samego postulatu.</p></div>
          </div>
          <div class="relnote"><b>Znaczenie dla stanowiska</b>Filar finansowania i infrastruktury to naturalny pretekst do rozmów z funduszami VC i dużymi dostawcami infrastruktury - dwoma segmentami niemal nieobecnymi dziś na liście członków.</div>
        ` },
        { id: 'cs-3', label: "Bruksela i NCBR", html: `
          <div class="cs-hero"><span class="client"><span class="sq"></span>Wydarzenie · Bruksela</span>
            <h3>Premiera raportu w Brukseli we współpracy z NCBR</h3>
            <p>W lipcu 2025 roku izba zorganizowała w Brukseli wydarzenie na styku prezydencji polskiej i duńskiej w Radzie UE, prezentując raport o MŚP. Partnerem był Narodowe Centrum Badań i Rozwoju<sup class="fn" tabindex="0" role="button" aria-label="Przypis 18, 14 — pokaż źródło" data-refs="18,14" data-fn="76">18,14<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em><br><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em></span></sup>.</p>
            <div class="scope"><span class="pill">partner publiczny</span><span class="pill">timing prezydencji</span><span class="pill">poziom unijny</span></div></div>
          <div class="steps">
            <div class="step"><div class="lbl">Kontekst</div><h4>Zmiana prezydencji jako okno uwagi</h4><p>Moment przejścia między prezydencjami zwiększa dostępność decydentów i uwagę mediów brukselskich.</p></div>
            <div class="step"><div class="lbl">Rola AI Chamber</div><h4>Organizacja i partnerstwo instytucjonalne</h4><p>Współpraca z NCBR dała wydarzeniu wiarygodność instytucjonalną i dostęp do sieci kontaktów po stronie publicznej.</p></div>
            <div class="step"><div class="lbl">Rezultat</div><h4>Obecność izby w Brukseli</h4><p>Powiązanie dorobku badawczego z obecnością na poziomie unijnym; model do powtórzenia przy kolejnych publikacjach.</p></div>
          </div>
          <div class="relnote"><b>Znaczenie dla stanowiska</b>Wzorzec współpracy z instytucją publiczną jako dźwignia wiarygodności - ten sam mechanizm działa przy pozyskiwaniu partnerów korporacyjnych, którzy kupują dostęp do decydentów, a nie samo logo.</div>
        ` },
        { id: 'cs-4', label: "Digital Omnibus", html: `
          <div class="cs-hero"><span class="client"><span class="sq"></span>Advocacy · koalicja 13 organizacji</span>
            <h3>Open Letter w sprawie Digital Omnibus</h3>
            <p>W grudniu 2025 roku izba wystąpiła wspólnie z dwunastoma innymi organizacjami regionu z listem otwartym dotyczącym pakietu Digital Omnibus<sup class="fn" tabindex="0" role="button" aria-label="Przypis 17 — pokaż źródło" data-refs="17" data-fn="77">17<span class="fc" role="note"><b>17.</b> AI Chamber wraz z dwunastoma innymi organizacjami regionu, list otwarty w sprawie pakietu Digital Omnibus, grudzień 2025 r. <em>M1</em></span></sup> - inicjatywy upraszczającej i przesuwającej część obowiązków cyfrowych w Unii<sup class="fn" tabindex="0" role="button" aria-label="Przypis 4 — pokaż źródło" data-refs="4" data-fn="78">4<span class="fc" role="note"><b>4.</b> Komisja Europejska, pakiet Digital Omnibus - propozycja uproszczenia przepisów cyfrowych i przesunięcia terminów stosowania obowiązków, listopad 2025 r. <em>M1</em></span></sup>.</p>
            <div class="scope"><span class="pill">13 organizacji</span><span class="pill">koalicja regionalna</span><span class="pill">grudzień 2025</span></div></div>
          <div class="steps">
            <div class="step"><div class="lbl">Sprawa</div><h4>Uproszczenie obowiązków cyfrowych</h4><p>Pakiet Digital Omnibus przesunął m.in. terminy stosowania obowiązków dla systemów AI wysokiego ryzyka<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 4, 3 — pokaż źródło" data-refs="4,3" data-fn="79">4,3<span class="fc" role="note"><b>4.</b> Komisja Europejska, pakiet Digital Omnibus - propozycja uproszczenia przepisów cyfrowych i przesunięcia terminów stosowania obowiązków, listopad 2025 r. <em>M1</em><br><b>3.</b> Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2024/1689 z dnia 13 czerwca 2024 r. ustanawiające zharmonizowane przepisy dotyczące sztucznej inteligencji (akt w sprawie sztucznej inteligencji), Dziennik Urzędowy Unii Europejskiej, seria L, 2024/1689. <em>M1</em></span></sup> - kwestię o bezpośrednim znaczeniu dla firm członkowskich.</p></div>
            <div class="step"><div class="lbl">Rola AI Chamber</div><h4>Współsygnowanie i budowa koalicji</h4><p>Zebranie wspólnego głosu trzynastu organizacji z regionu zamiast wystąpienia pojedynczego podmiotu.</p></div>
            <div class="step"><div class="lbl">Rezultat</div><h4>Dowód realnej reprezentacji interesów</h4><p>Materialny dowód na to, że filar Representation of Interests nie jest hasłem marketingowym - koalicja daje wagę, której pojedyncza firma MŚP nie osiągnie samodzielnie.</p></div>
          </div>
          <div class="relnote"><b>Znaczenie dla stanowiska</b>Najsilniejszy argument sprzedażowy przy MŚP: samodzielna firma o pięciu pracownikach nie ma szans wpłynąć na regulację unijną, koalicja trzynastu organizacji ma. To odpowiedź na najczęstszą obiekcję: „po co nam składka”.</div>
        ` },
        { id: 'cs-5', label: "CEE AI Summit 2026", html: `
          <div class="cs-hero"><span class="client"><span class="sq"></span>Wydarzenie flagowe · Praga</span>
            <h3>CEE AI Summit 2026 - 3 września, Martinic Palace</h3>
            <p>Flagowa konferencja regionalna zaplanowana na 3 września 2026 roku w Pradze, pod auspicjami czeskiego Ministerstwa Przemysłu i Handlu<sup class="fn" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="80">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>. Wśród zapowiadanych mówców komisarz UE ds. startupów, badań i innowacji oraz wicepremierzy Czech i Polski<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="81">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>.</p>
            <div class="scope"><span class="pill">03.09.2026</span><span class="pill">patronat ministerialny</span><span class="pill">poziom komisarski</span></div></div>
          <div class="steps">
            <div class="step"><div class="lbl">Format</div><h4>Szczyt regionalny z rangą rządową</h4><p>Lokalizacja w Martinic Palace przy Zamku Praskim i auspicje czeskiego ministerstwa nadają wydarzeniu rangę wykraczającą poza konferencję branżową.</p></div>
            <div class="step"><div class="lbl">Rola AI Chamber</div><h4>Organizator i gospodarz agendy</h4><p>Izba buduje wydarzenie jako regularny punkt w kalendarzu regionu, a nie jednorazową inicjatywę - edycje wcześniejsze poprzedziły tę w Pradze.</p></div>
            <div class="step"><div class="lbl">Rezultat</div><h4>Kalendarzowy kamień milowy</h4><p>Termin wrześniowy jest istotny operacyjnie: to najbliższe duże wydarzenie po zatrudnieniu, a jednocześnie naturalna okazja do pozyskiwania leadów i domykania partnerstw.</p></div>
          </div>
          <div class="relnote"><b>Znaczenie dla stanowiska</b>Oferta wprost wymienia wspieranie lead generation i networkingu podczas wydarzeń krajowych i międzynarodowych. Praga 3 września 2026 to pierwszy sprawdzalny termin, wobec którego można zaplanować konkretne działania - warto przyjść na rozmowę z gotowym pomysłem na ten szczyt.</div>
        ` },
        { id: 'cs-6', label: "Ustawa o AI", html: `
          <div class="cs-hero"><span class="client"><span class="sq"></span>Konsultacje · Polska i Komisja Europejska</span>
            <h3>Stanowiska konsultacyjne wobec ustawy o AI i przepisów unijnych</h3>
            <p>Izba złożyła oficjalne stanowisko w Ministerstwie Cyfryzacji wobec projektu ustawy o systemach sztucznej inteligencji<sup class="fn" tabindex="0" role="button" aria-label="Przypis 18, 5 — pokaż źródło" data-refs="18,5" data-fn="82">18,5<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em><br><b>5.</b> Ustawa o systemach sztucznej inteligencji: projekt przyjęty przez Radę Ministrów 31 marca 2026 r., uchwalony przez Sejm Rzeczypospolitej Polskiej głosami 421 posłów, podpisany przez Prezydenta RP, 2026 r. <em>M1</em></span></sup> oraz wobec dokumentu „Polityka rozwoju AI w Polsce do 2030 roku”<sup class="fn" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="83">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>. Uczestniczyła również w konsultacjach Komisji Europejskiej dotyczących klasyfikacji systemów wysokiego ryzyka<sup class="fn" tabindex="0" role="button" aria-label="Przypis 18, 3 — pokaż źródło" data-refs="18,3" data-fn="84">18,3<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em><br><b>3.</b> Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2024/1689 z dnia 13 czerwca 2024 r. ustanawiające zharmonizowane przepisy dotyczące sztucznej inteligencji (akt w sprawie sztucznej inteligencji), Dziennik Urzędowy Unii Europejskiej, seria L, 2024/1689. <em>M1</em></span></sup> oraz prawa autorskiego i eksploracji tekstów i danych<sup class="fn" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="85">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>.</p>
            <div class="scope"><span class="pill">Ministerstwo Cyfryzacji</span><span class="pill">konsultacje KE</span><span class="pill">art. 6 AI Act</span></div></div>
          <div class="steps">
            <div class="step"><div class="lbl">Zakres</div><h4>Poziom krajowy i unijny równolegle</h4><p>Prace obejmowały krajowy proces ustawodawczy oraz konsultacje unijne dotyczące klasyfikacji high-risk i kwestii praw autorskich w kontekście trenowania modeli.</p></div>
            <div class="step"><div class="lbl">Rola AI Chamber</div><h4>Rzecznik interesu firm z sektora</h4><p>Udział w AI Action Summit w Paryżu ze współorganizacją panelu na zaproszenie Ambasady RP<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="86">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup> dopełnił obraz obecności na poziomie międzynarodowym.</p></div>
            <div class="step"><div class="lbl">Rezultat</div><h4>Pozycja w procesie decyzyjnym</h4><p>Polska ustawa o systemach AI ustanawia Komisję Rozwoju i Bezpieczeństwa Sztucznej Inteligencji jako organ nadzoru<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 5 — pokaż źródło" data-refs="5" data-fn="87">5<span class="fc" role="note"><b>5.</b> Ustawa o systemach sztucznej inteligencji: projekt przyjęty przez Radę Ministrów 31 marca 2026 r., uchwalony przez Sejm Rzeczypospolitej Polskiej głosami 421 posłów, podpisany przez Prezydenta RP, 2026 r. <em>M1</em></span></sup>; izba brała udział w kształtowaniu tego procesu na etapie konsultacji<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="88">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>.</p></div>
          </div>
          <div class="relnote"><b>Znaczenie dla stanowiska</b>To dowód, że składka kupuje wpływ na konkretne dokumenty, a nie abstrakcyjną reprezentację. W rozmowie sprzedażowej działa lepiej niż deklaracje: można wskazać nazwę projektu ustawy i etap, na którym izba się wypowiedziała.</div>
        ` },
      ],
    },
  ],
};
