import type { DossierPage } from './types';

export const pageOferta: DossierPage = {
  id: 'oferta',
  num: '10',
  navLabel: "Oferta i dopasowanie",
  group: "Kandydat",
  eyebrow: "10 · Kandydat",
  title: `Oferta: Partnerships &amp; Membership Growth Manager`,
  lead: `Ogłoszenie AI Chamber na stanowisko odpowiadające za rozwój bazy członkowskiej i partnerstw w regionie CEE<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="168">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>. Poniżej treść oferty, dopasowanie punkt po punkcie do doświadczenia z CV, ocena poziomu stanowiska oraz analiza modelu wynagrodzenia.`,
  blocks: [
    { kind: 'html', html: `<div class="metrics c4">
        <div class="metric"><div class="n">Zdalnie</div><div class="l">tryb pracy (remote cooperation)<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="169">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></div></div>
        <div class="metric"><div class="n">1/2 lub 1/1</div><div class="l">part-time albo full-time - do wyboru<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="170">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></div></div>
        <div class="metric amber"><div class="n">5+ lat</div><div class="l">wymagane doświadczenie (BD wg publikującego)<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="171">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></div></div>
        <div class="metric cyan"><div class="n">Baza + %</div><div class="l">model wynagrodzenia z prowizją od wyników<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="172">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></div></div>
      </div>
<p class="note" style="margin-top:12px">Aplikacja: CV na adres contact@aichamber.eu<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="173">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>. W ogłoszeniu nie podano widełek wynagrodzenia, terminu zgłoszeń ani informacji, czy stanowisko jest nowe<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="174">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>. Wymagania dodane przez publikującego: ponad 3 lata doświadczenia w Sales oraz ponad 5 lat w Business Development<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="175">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>.</p>
<div class="verdict block" style="margin-top:20px">
        <h4>Dopasowanie - synteza</h4>
        <p>Rdzeń oferty to proaktywny outreach, prowadzenie pełnego cyklu zaangażowania, prezentowanie oferty członkowskiej i partnerskiej, praca na własnym pipeline'ie oraz networking na wydarzeniach<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="176">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>. W czterech z tych pięciu obszarów profil kandydata ma udokumentowane rezultaty; wyraźnie przewyższa wymóg językowy (C1 wobec „very good”) oraz punkt określony w ofercie jako atut dodatkowy, czyli zainteresowanie AI, technologią, innowacjami i polityką publiczną. Realna luka jest jedna, ale istotna: brak dedykowanej roli sprzedażowej lub business development z formalnym celem, wobec wymogu 5 lat w BD i 3 lat w sprzedaży. Legenda statusów: <span class="pill pos">spełnia</span> <span class="pill warn">częściowo</span> <span class="pill cyan">do wykazania</span></p>
      </div>
<h3 class="mono" style="color:var(--muted);font-size:11px;margin:26px 0 4px">ZAKRES OBOWIĄZKÓW<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="177">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup> - DOPASOWANIE<sup class="fn" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="178">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup></h3>
<div class="card">
        <ul class="matters">
          <li><span class="pill warn">częściowo</span> Rozwijanie bazy członkowskiej i partnerskiej przez proaktywny outreach i budowanie relacji - pozyskanie 14 partnerów i sponsorów dla EFC oraz 25 partnerów konferencji; brak jednak pracy w modelu z przypisanym celem sprzedażowym i kwotą.</li>
          <li><span class="pill pos">spełnia</span> Prowadzenie pełnego cyklu zaangażowania: identyfikacja prospektów, inicjowanie kontaktu, rozmowy, doprowadzenie do przystąpienia - sekwencje lead nurturing w LinkedIn Sales Navigator dla działów eksportu (Elektronika) oraz pozyskiwanie partnerów kongresowych od pierwszego kontaktu do umowy (EFC).</li>
          <li><span class="pill pos">spełnia</span> Prezentowanie oferty członkowskiej i partnerskiej oraz komunikowanie jej wartości - opracowanie oferty świadczeń NES wraz z wyceną, czyli zaprojektowanie propozycji wartości od zera, a nie tylko jej przedstawianie.</li>
          <li><span class="pill pos">spełnia</span> Budowanie i utrzymywanie relacji z prospektami i obecnymi interesariuszami - sieć ponad 100 współpracowników NES, w tym rady programowe i eksperci zagraniczni, utrzymywana w trybie ciągłym.</li>
          <li><span class="pill pos">spełnia</span> Wspieranie lead generation i networkingu podczas wydarzeń krajowych i międzynarodowych - trzy edycje konferencji własnej, kongres EFC, przygotowanie zaangażowania NES w Ukraine Recovery Conference 2026 w Gdańsku.</li>
          <li><span class="pill pos">spełnia</span> Współpraca z zespołem wewnętrznym nad inicjatywami wzrostowymi, kampaniami i strategiami zaangażowania - kampanie płatne i organiczne w rolach marketingowych, koordynacja zespołów w NES i Linkleaders.</li>
          <li><span class="pill warn">częściowo</span> Wdrażanie działań retencyjnych wzmacniających relacje długoterminowe - automatyzacja i segmentacja komunikacji z bazą (+43% subskrybentów r/r w Niczuku), sekwencje utrzymaniowe; brak doświadczenia w retencji członkowskiej rozliczanej wskaźnikiem odnowień.</li>
          <li><span class="pill pos">spełnia</span> Utrzymywanie danych w CRM i raportowanie działań outreachowych - praca w HubSpot i Pipedrive, wdrożenie CRM i marketing automation w EFC, budowa trackerów raportujących efekty działań.</li>
        </ul>
      </div>
<h3 class="mono" style="color:var(--muted);font-size:11px;margin:26px 0 4px">WYMAGANIA<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="179">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup> - SPEŁNIONE<sup class="fn" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="180">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup></h3>
<div class="card">
        <ul class="matters">
          <li><span class="pill pos">przewyższa</span> Bardzo dobry angielski w mowie i piśmie - poziom C1; dodatkowo hiszpański C1 i doświadczenie w obsłudze rynków hiszpańskojęzycznych w Refinitiv / LSEG.</li>
          <li><span class="pill pos">przewyższa</span> Zainteresowanie AI, technologią, innowacjami lub polityką publiczną (w ofercie jako atut) - prowadzenie think tanku zajmującego się geopolityką i technologią, budowa własnej platformy SaaS, praca magisterska z obszaru geostrategii; to podstawa działalności zawodowej, nie deklaracja.</li>
          <li><span class="pill pos">spełnia</span> Pewność w outreachu i bezpośredniej komunikacji z potencjalnymi partnerami i członkami - pozyskiwanie sponsorów i partnerów honorowych kongresu, kontakt z prelegentami i mediami, rekrutacja rad programowych.</li>
          <li><span class="pill pos">spełnia</span> Silne kompetencje interpersonalne i komunikacyjne - koordynacja ponad 100 współpracowników, praca doradcza z klientem korporacyjnym, wystąpienia i prowadzenie debat.</li>
          <li><span class="pill pos">spełnia</span> Wysoki poziom energii, proaktywność i wytrwałość - talenty Gallupa Aktywator i Osiąganie; założenie i prowadzenie fundacji równolegle do pracy zawodowej.</li>
          <li><span class="pill pos">spełnia</span> Zdolność do samodzielnej pracy i zarządzania własnym pipeline'em - budowa i prowadzenie sekwencji w Sales Navigator, samodzielne prowadzenie projektów od koncepcji do rozliczenia efektu.</li>
          <li><span class="pill pos">spełnia</span> Doświadczenie w środowisku B2B - eksport przemysłowy (Thale/Niczuk, Elektronika), doradztwo dla klientów korporacyjnych (Linkleaders), rynek finansowy (Refinitiv / LSEG).</li>
          <li><span class="pill pos">spełnia</span> Praca w organizacji międzynarodowej działającej w regionie CEE - obsługa czterech rynków zagranicznych w strategii sprzedażowej Niczuka, praca na rynkach Ameryki Południowej i Hiszpanii w LSEG, sieć ekspertów zagranicznych w NES.</li>
          <li><span class="pill pos">spełnia</span> Gotowość do pracy zdalnej - obecna praca w modelu rozproszonym, doświadczenie w koordynacji zespołów zdalnych i wydarzeń online.</li>
        </ul>
      </div>
<h3 class="mono" style="color:var(--muted);font-size:11px;margin:26px 0 4px">WYMAGANIA<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="181">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup> - CZĘŚCIOWO LUB DO WYKAZANIA<sup class="fn" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="182">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup></h3>
<div class="card">
        <ul class="matters">
          <li><span class="pill warn">częściowo</span> Ponad 5 lat doświadczenia w partnerstwach, business development, sprzedaży lub zarządzaniu relacjami z interesariuszami - siedem lat i dziewięć miesięcy pracy zawodowej, z komponentem partnerstw i pozyskiwania obecnym w EFC, NES i projektach konferencyjnych; nazwa stanowiska nigdy jednak nie brzmiała business development ani sales.</li>
          <li><span class="pill cyan">do wykazania</span> Ponad 3 lata doświadczenia w Sales (wymóg dodany przez publikującego) - brak roli sprzedażowej z kwotą; do wykazania przez konkretne liczby pozyskanych partnerów i wartość zamkniętych porozumień.</li>
          <li><span class="pill warn">częściowo</span> Ponad 5 lat doświadczenia w Business Development (wymóg dodany przez publikującego) - realnie około czterech lat aktywności rozwojowej liczonej od EFC (sierpień 2021), obejmującej pozyskiwanie partnerów, tworzenie oferty i wejścia na nowe rynki.</li>
          <li><span class="pill cyan">do wykazania</span> Doświadczenie w sprzedaży członkostwa w organizacji członkowskiej - brak; do zaadresowania przez pokazanie zrozumienia mechaniki (retencja pierwszoroczna<sup class="fn" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="183">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup>, automatyczne odnowienie<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="184">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>, wartość advocacy dla MŚP<sup class="fn" tabindex="0" role="button" aria-label="Przypis 17 — pokaż źródło" data-refs="17" data-fn="185">17<span class="fc" role="note"><b>17.</b> AI Chamber wraz z dwunastoma innymi organizacjami regionu, list otwarty w sprawie pakietu Digital Omnibus, grudzień 2025 r. <em>M1</em></span></sup>) oraz gotowego planu z zakładki 14.</li>
          <li><span class="pill cyan">do wykazania</span> Sieć kontaktów w regionie CEE poza Polską - kontakty zagraniczne w ramach NES i obsługa rynków eksportowych; brak zbudowanej sieci sprzedażowej w Czechach, Rumunii czy na Węgrach.</li>
        </ul>
        <p class="note" style="margin-top:12px">Uwaga metodyczna: wymogi stażowe w ogłoszeniach tego typu są zwykle filtrem wstępnym, nie warunkiem bezwzględnym. Przy roli, w której liczy się rezultat mierzalny liczbą pozyskanych podmiotów, mocniejszym argumentem od nazwy stanowiska są konkretne liczby - i te kandydat ma.</p>
      </div>
<div class="grid3 block" style="margin-top:20px">
        <div class="card"><h3 class="mono" style="color:var(--muted);font-size:11px">FORMA I MIEJSCE</h3>
          <div class="chips" style="margin-top:10px"><span class="chip">praca zdalna</span><span class="chip">część lub pełny etat</span><span class="chip">organizacja międzynarodowa</span><span class="chip">region CEE</span></div>
        </div>
        <div class="card"><h3 class="mono" style="color:var(--muted);font-size:11px">CO OFERUJĄ<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="186">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></h3>
          <div class="chips" style="margin-top:10px"><span class="chip">baza plus prowizja od wyników</span><span class="chip">wynagrodzenie wobec kompetencji i osiągnięć</span><span class="chip">dostęp do wydarzeń i ekspertów AI</span><span class="chip">bezpośredni wpływ na ekosystem</span></div>
        </div>
        <div class="card"><h3 class="mono" style="color:var(--muted);font-size:11px">KANAŁ APLIKACJI<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="187">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></h3>
          <div class="chips" style="margin-top:10px"><span class="chip">CV na contact@aichamber.eu</span><span class="chip">brak systemu ATS</span><span class="chip">brak terminu w ogłoszeniu</span></div>
        </div>
      </div>
<h3 class="mono" style="color:var(--muted);font-size:11px;margin:26px 0 4px">KANAŁ APLIKACJI - KONSEKWENCJE PRAKTYCZNE</h3>
<div class="card">
        <p>Aplikacja odbywa się przez e-mail na ogólny adres organizacji, bez systemu rekrutacyjnego<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="188">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>. To zmienia sytuację w trzech wymiarach w porównaniu z rekrutacją prowadzoną przez portal pracy.</p>
        <table class="data" style="margin-top:12px">
          <thead><tr><th>Wymiar</th><th>Stan faktyczny</th><th>Konsekwencja</th></tr></thead>
          <tbody>
            <tr><td>Dane o konkurencji</td><td>brak jakichkolwiek statystyk puli kandydatów</td><td>nie da się ocenić pozycji na tle innych; nie należy zakładać ani przewagi, ani jej braku</td></tr>
            <tr><td>Status aplikacji</td><td>brak informacji zwrotnej z systemu</td><td>uzasadniony follow-up po 7-10 dniach roboczych</td></tr>
            <tr><td>Adresat</td><td>skrzynka ogólna contact@aichamber.eu<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="189">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></td><td>warto skierować treść wprost do osoby odpowiedzialnej za obszar (Director of Growth &amp; Partnerships)<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 11, 31 — pokaż źródło" data-refs="11,31" data-fn="190">11,31<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em><br><b>31.</b> Profile zawodowe w serwisie LinkedIn: Tomasz Snażyk, Agnieszka Gosztyła, Marcin Olender, Monika Kalkusová, Paulina Król oraz członkowie Board of Directors i Board of Advisors; odczyt: sierpień 2026. <em>M3</em></span></sup></td></tr>
            <tr><td>Termin</td><td>brak daty zamknięcia w ogłoszeniu</td><td>rekrutacja prawdopodobnie prowadzona do znalezienia kandydata - szybkość aplikacji ma znaczenie</td></tr>
            <tr><td>Format</td><td>wymagane tylko CV, bez listu</td><td>list przewodni jako element wyróżniający, nie obowiązkowy; naturalne miejsce na tezę o dopasowaniu</td></tr>
          </tbody>
        </table>
        <p class="note" style="margin-top:12px">Rekomendacja: skoro kanał jest e-mailowy i nieustandaryzowany, przewagę daje treść, nie zgodność z formularzem. Krótka wiadomość z jedną konkretną obserwacją o organizacji (na przykład o luce w reprezentacji rynku czeskiego przed szczytem w Pradze) działa lepiej niż standardowe CV bez kontekstu.</p>
      </div>
<h3 class="mono" style="color:var(--muted);font-size:11px;margin:26px 0 4px">POZIOM STANOWISKA - OCENA ZAKRESU</h3>
<div class="card">
        <p>Tytuł zawiera słowo Manager, ale w ogłoszeniu nie ma zarządzania zespołem. Ocena poniżej porządkuje, które elementy odpowiadają poziomowi samodzielnego specjalisty, a które sięgają wyżej.</p>
        <table class="data" style="margin-top:12px">
          <thead><tr><th>Wymiar</th><th>Zapis w ofercie</th><th>Poziom</th></tr></thead>
          <tbody>
            <tr><td>Tytuł</td><td>Partnerships &amp; Membership Growth Manager<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="191">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup></td><td><span class="pill">manager bez zespołu</span></td></tr>
            <tr><td>Próg wejścia</td><td>ponad 5 lat w partnerstwach, BD, sprzedaży lub stakeholder engagement</td><td><span class="pill">senior specjalista</span></td></tr>
            <tr><td>Zadania wykonawcze</td><td>outreach, rozmowy, prezentacja oferty, obsługa CRM</td><td><span class="pill">specjalista</span></td></tr>
            <tr><td>Autonomia</td><td>samodzielna praca i zarządzanie własnym pipeline'em</td><td><span class="pill warn">powyżej poziomu</span></td></tr>
            <tr><td>Własność wyniku</td><td>wzrost bazy członkowskiej i partnerskiej jako cel roli</td><td><span class="pill warn">powyżej poziomu</span></td></tr>
            <tr><td>Szerokość zakresu</td><td>akwizycja, prezentacja oferty, relacje, wydarzenia, kampanie, retencja, CRM</td><td><span class="pill warn">pełny cykl komercyjny</span></td></tr>
            <tr><td>Zarządzanie ludźmi</td><td>brak w opisie</td><td><span class="pill">nie dotyczy</span></td></tr>
            <tr><td>Władztwo budżetowe</td><td>brak w opisie</td><td><span class="pill">nie dotyczy</span></td></tr>
            <tr><td>Własność cennika i warunków</td><td>brak informacji - kluczowa niewiadoma</td><td><span class="pill cyan">do ustalenia</span></td></tr>
            <tr><td>Raportowanie</td><td>brak informacji; najprawdopodobniej do Director of Growth &amp; Partnerships<sup class="fn" tabindex="0" role="button" aria-label="Przypis 11, 31 — pokaż źródło" data-refs="11,31" data-fn="192">11,31<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em><br><b>31.</b> Profile zawodowe w serwisie LinkedIn: Tomasz Snażyk, Agnieszka Gosztyła, Marcin Olender, Monika Kalkusová, Paulina Król oraz członkowie Board of Directors i Board of Advisors; odczyt: sierpień 2026. <em>M3</em></span></sup></td><td><span class="pill cyan">do ustalenia</span></td></tr>
          </tbody>
        </table>
      </div>
<div class="verdict block" style="margin-top:16px">
        <h4>Wniosek</h4>
        <p>To rola samodzielnego seniora odpowiedzialnego za wynik komercyjny, nie stanowisko menedżerskie w sensie zarządzania ludźmi<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="193">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>. Słowo Manager odnosi się do zarządzania procesem i pipeline'em, a nie zespołem. Praktyczna konsekwencja jest dwojaka. Po pierwsze, przy około 90 członkach i braku publicznego cennika osoba na tym stanowisku będzie w dużej mierze projektować proces, nie tylko go wykonywać - to argument za wyższą bazą i za pytaniem o zakres decyzyjności w sprawie warunków. Po drugie, brak informacji o tym, kto posiada cennik i jaki jest obecny pipeline, jest najważniejszą luką do domknięcia przed jakąkolwiek rozmową o liczbach.</p>
      </div>
<h3 class="mono" style="color:var(--muted);font-size:11px;margin:26px 0 4px">WYNAGRODZENIE - MODEL BAZA PLUS PROWIZJA</h3>
<div class="card">
        <p>Oferta przewiduje wynagrodzenie zasadnicze uzupełnione atrakcyjną prowizją od wyników, a poziom ma odpowiadać kompetencjom i udokumentowanym osiągnięciom<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="194">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>. Nie podano żadnych kwot, dlatego poniższe wartości są benchmarkami rynkowymi, nie danymi pracodawcy.</p>
        <table class="data" style="margin-top:12px">
          <thead><tr><th>Parametr</th><th>Benchmark rynkowy</th><th>Uwagi</th></tr></thead>
          <tbody>
            <tr><td>Średnia dla stanowisk specjalistycznych i menedżerskich w Polsce</td><td>około 15 700 zł brutto</td><td>Antal Salary Report<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 30 — pokaż źródło" data-refs="30" data-fn="195">30<span class="fc" role="note"><b>30.</b> Antal, raport płacowy, 2025/2026 - średnia dla stanowisk specjalistycznych i menedżerskich około 15 700 zł brutto; kategoria szeroka, nieodnosząca się do tej konkretnej roli. <em>M2</em></span></sup>; szeroka kategoria, nie dotyczy tej konkretnej roli</td></tr>
            <tr><td>Dynamika wynagrodzeń 2025/2026</td><td>80% firm podniosło płace, większość o 2,5-5%</td><td>Hays Poland Salary Guide 2026<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 29 — pokaż źródło" data-refs="29" data-fn="196">29<span class="fc" role="note"><b>29.</b> Hays Poland, „Salary Guide 2026”, 2026 r. - 80% firm podniosło wynagrodzenia, w większości o 2,5-5%. <em>M2</em></span></sup> - rynek stabilizacji, nie wzrostu</td></tr>
            <tr><td>Typowy podział baza do części zmiennej w B2B</td><td>od 50/50 do 60/40</td><td>im krótszy cykl i jaśniejsza atrybucja, tym wyższa część zmienna</td></tr>
            <tr><td>Podział przy długim cyklu i zarządzaniu relacją</td><td>około 70/30</td><td>właściwy punkt odniesienia dla sprzedaży członkostwa</td></tr>
            <tr><td>Poziom prowizji w B2B</td><td>5-20% w zależności od produktu i roli</td><td>przy subskrypcji zwykle procent od pierwszej składki plus element za odnowienie</td></tr>
            <tr><td>Wariant part-time</td><td>baza proporcjonalna, prowizja bez proporcjonalizacji</td><td>przy części etatu warto negocjować wyższą stawkę prowizyjną, nie wyższą bazę</td></tr>
          </tbody>
        </table>
        <div class="matters-title" style="margin-top:14px">Argumenty wspierające wyższą bazę</div>
        <ul class="matters">
          <li>Brak publicznego cennika i ustandaryzowanego procesu<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="197">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup> oznacza dłuższy cykl sprzedaży i mniej przewidywalną atrybucję wyniku w pierwszych miesiącach.</li>
          <li>Zakres obejmuje nie tylko akwizycję, ale też retencję, obsługę CRM, wydarzenia i współpracę nad kampaniami - część tych zadań nie generuje prowizji, choć zajmuje czas.</li>
          <li>Rola wymaga budowy procesu od podstaw przy bazie około 90 członków<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="198">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, a nie obsługi gotowego pipeline'u.</li>
          <li>Praca zdalna na region dziewięciu krajów wymaga samodzielnej organizacji pracy i pokrycia kosztów własnych narzędzi.</li>
        </ul>
        <div class="matters-title" style="margin-top:14px">Do ustalenia przed podaniem liczby</div>
        <ul class="matters">
          <li>Poziomy cenowe pakietów BASIC, PRO, PREMIUM oraz partnerstw korporacyjnych<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10, 11 — pokaż źródło" data-refs="10,11" data-fn="199">10,11<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em><br><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em></span></sup> - bez nich nie da się oszacować realnej wartości prowizji.</li>
          <li>Podstawa prowizji: pierwsza składka, wartość roczna kontraktu czy również odnowienia.</li>
          <li>Cel liczbowy na rok oraz obecny punkt wyjścia (liczba nowych członków w ostatnich dwunastu miesiącach).</li>
          <li>Forma współpracy: umowa o pracę, zlecenie czy kontrakt B2B - determinuje przeliczenie kwoty netto.</li>
          <li>Wymiar etatu: przy części etatu proporcje bazy i prowizji powinny się przesunąć na korzyść prowizji.</li>
        </ul>
        <p class="note" style="margin-top:12px">Rekomendacja negocjacyjna: nie podawać twardej liczby przed poznaniem poziomów cenowych i celu. Właściwa kolejność to najpierw pytanie o cennik i cel, potem propozycja podziału bliżej 70/30 na rzecz bazy w pierwszym roku, z możliwością przesunięcia w stronę 60/40 po ustabilizowaniu procesu. Wszystkie kwoty w tabeli są benchmarkami rynkowymi z raportów płacowych<sup class="fn" tabindex="0" role="button" aria-label="Przypis 29, 30 — pokaż źródło" data-refs="29,30" data-fn="200">29,30<span class="fc" role="note"><b>29.</b> Hays Poland, „Salary Guide 2026”, 2026 r. - 80% firm podniosło wynagrodzenia, w większości o 2,5-5%. <em>M2</em><br><b>30.</b> Antal, raport płacowy, 2025/2026 - średnia dla stanowisk specjalistycznych i menedżerskich około 15 700 zł brutto; kategoria szeroka, nieodnosząca się do tej konkretnej roli. <em>M2</em></span></sup>, a nie informacją od pracodawcy.</p>
      </div>
<div class="verdict cyan block" style="margin-top:20px">
        <h4>Luki i rekomendacje na rozmowę</h4>
        <p>Trzy obszary wymagają zaadresowania. Po pierwsze, formalny staż w rolach nazwanych business development lub sales - odpowiedź: pokazać liczby zamiast nazw stanowisk (14 partnerów EFC, 25 partnerów konferencji, 100+ interesariuszy NES) i wskazać, że każdy z tych rezultatów wymagał tego samego zestawu czynności, jakie opisuje ogłoszenie. Po drugie, brak doświadczenia w sprzedaży członkostwa - odpowiedź: pokazać zrozumienie mechaniki tego produktu, w szczególności roli retencji pierwszorocznej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="201">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup> i automatycznego odnowienia z terminem 31 grudnia<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="202">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>, oraz przyjść z gotowym planem (zakładka 14). Po trzecie, sieć kontaktów w CEE poza Polską - odpowiedź: nie udawać, że istnieje, a zamiast tego zaproponować konkretną ścieżkę jej budowy z wykorzystaniem Board of Advisors<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="203">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup> i szczytu w Pradze<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="204">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>. Kotwica narracyjna: kandydat, który sam zbudował instytucję pozyskującą partnerów i utrzymującą stu współpracowników, rozumie produkt członkowski z drugiej strony stołu - wie, za co organizacja członkowska realnie pobiera składkę, bo sam taką wartość projektował i wyceniał.</p>
      </div>` },
  ],
};
