import type { DossierPage } from './types';

export const pagePlan: DossierPage = {
  id: 'plan',
  num: '14',
  navLabel: "Plan wzrostu",
  group: "Analiza rynkowa",
  eyebrow: "14 · Analiza rynkowa",
  title: `Co bym zrobił, aby zwiększyć bazę członkowską i partnerską`,
  lead: `Plan działania wynikający z analizy modelu przychodowego (zakładka 04), struktury bazy (zakładka 06) i otoczenia rynkowego (zakładka 13). Cel: zwiększyć liczbę członków oraz wartość partnerstw korporacyjnych, przy jednoczesnej poprawie retencji. Punkt wyjścia: około 90 członków<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="300">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, brak publicznego cennika<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="301">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>, sześć z dziewięciu rynków o reprezentacji symbolicznej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="302">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, silne aktywa w postaci rady doradczej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="303">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>, dorobku badawczego<sup class="fn" tabindex="0" role="button" aria-label="Przypis 14, 13 — pokaż źródło" data-refs="14,13" data-fn="304">14,13<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em><br><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em></span></sup> i wydarzenia flagowego<sup class="fn" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="305">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>.`,
  blocks: [
    {
      kind: 'tabs',
      group: 'wz',
      tabs: [
        { id: 'wz-1', label: "Akwizycja i pipeline", html: `
          <p class="axis-intro">Diagnoza: baza około 90 firm<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="306">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, brak publicznego cennika<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="307">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>, brak informacji o ustandaryzowanym procesie sprzedaży. Przy takim punkcie wyjścia szybciej opłaca się zbudować powtarzalny proces niż zwiększać liczbę przypadkowych rozmów.</p>
          <div class="card">
            <div class="matters-title">Co bym zrobił</div>
            <ul class="matters">
              <li>Przeprowadzić analizę obecnej bazy: skąd przyszli dotychczasowi członkowie, które sektory i wielkości firm konwertują najszybciej, którzy członkowie są najbardziej aktywni. To jedyny sposób, by kolejne działania opierać na wzorcu, a nie na przypuszczeniu.</li>
              <li>Zdefiniować profil idealnego członka osobno dla każdego pakietu (BASIC, PRO, PREMIUM)<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="308">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup> i przypisać do niego źródła kontaktów oraz argumentację.</li>
              <li>Priorytetyzować segmenty pod presją regulacyjną: MedTech, FinTech i dostawcy dla sektora publicznego, dla których wartość compliance z AI Act jest najbardziej odczuwalna<sup class="fn" tabindex="0" role="button" aria-label="Przypis 3 — pokaż źródło" data-refs="3" data-fn="309">3<span class="fc" role="note"><b>3.</b> Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2024/1689 z dnia 13 czerwca 2024 r. ustanawiające zharmonizowane przepisy dotyczące sztucznej inteligencji (akt w sprawie sztucznej inteligencji), Dziennik Urzędowy Unii Europejskiej, seria L, 2024/1689. <em>M1</em></span></sup>.</li>
              <li>Ustandaryzować materiał sprzedażowy oparty na danych z raportu izby<sup class="fn" tabindex="0" role="button" aria-label="Przypis 14 — pokaż źródło" data-refs="14" data-fn="310">14<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em></span></sup>: rozmowa zaczyna się od tego, gdzie stoi rynek rozmówcy, a nie od opisu izby.</li>
              <li>Uporządkować etapy lejka w CRM i wprowadzić tygodniowy rytm: liczba nowych rozmów, przegląd pipeline'u, raport konwersji po etapach.</li>
              <li>Wykorzystać sieć Board of Directors jako źródło referencji - pięć firm, które oddelegowały swoich ludzi do rady<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 8 — pokaż źródło" data-refs="8" data-fn="311">8<span class="fc" role="note"><b>8.</b> AI Chamber, „Board of Directors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>, to gotowa lista rekomendujących.</li>
              <li>Zaproponować uporządkowanie kwestii cennika, przynajmniej wewnętrznie: karta pakietów z widełkami i jasnym progiem decyzyjnym skraca cykl sprzedaży bardziej niż jakikolwiek zabieg komunikacyjny.</li>
            </ul>
            <p class="note" style="margin:2px 0 0">Pomiar: liczba nowych rozmów tygodniowo, konwersja między etapami, długość cyklu sprzedaży, liczba nowych członków w podziale na pakiety.</p>
          </div>
        ` },
        { id: 'wz-2', label: "Partnerstwa korporacyjne", html: `
          <p class="axis-intro">Diagnoza: ścieżka o najwyższej wartości jednostkowej kontraktu, przy bazie złożonej dziś głównie z mikro i małych firm<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="312">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>. Cztery filary oferty są zdefiniowane<sup class="fn" tabindex="0" role="button" aria-label="Przypis 11 — pokaż źródło" data-refs="11" data-fn="313">11<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em></span></sup>, ale nie ustalono liczby obecnych partnerów ani poziomów cenowych.</p>
          <div class="card">
            <div class="matters-title">Co bym zrobił</div>
            <ul class="matters">
              <li>Zbudować listę docelową dużych firm w regionie z podziałem na trzy grupy: dostawcy technologii AI, duzi odbiorcy wdrażający AI oraz podmioty z sektorów regulowanych (finanse, zdrowie, energetyka).</li>
              <li>Wykorzystać Board of Advisors jako otwieracza drzwi - byli ministrowie z czterech państw regionu<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="314">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup> to argument, którego nie ma żadna organizacja krajowa<sup class="fn" tabindex="0" role="button" aria-label="Przypis 25 — pokaż źródło" data-refs="25" data-fn="315">25<span class="fc" role="note"><b>25.</b> Digital Poland oraz European AI Forum, materiały własne organizacji, dostęp: sierpień 2026 - inicjatywa AIPoland, CEE Digital Coalition oraz skład założycielski forum europejskiego. <em>M2</em></span></sup>; Premium Connections jest najtrudniejszym do skopiowania elementem oferty<sup class="fn" tabindex="0" role="button" aria-label="Przypis 11 — pokaż źródło" data-refs="11" data-fn="316">11<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em></span></sup>.</li>
              <li>Zbudować pakiety wokół wydarzenia flagowego: CEE AI Summit 3 września 2026 w Pradze pod auspicjami czeskiego ministerstwa<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="317">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup> daje konkretny, datowany produkt do sprzedaży, a nie abstrakcyjne partnerstwo roczne.</li>
              <li>Wykorzystać dorobek badawczy jako uzasadnienie filaru Strategic Insights: raport z jedenastu krajów<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 14 — pokaż źródło" data-refs="14" data-fn="318">14<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em></span></sup> pokazuje, że izba dostarcza dane, a nie tylko streszczenia cudzych analiz.</li>
              <li>Sformalizować ofertę w postaci karty pakietów z widełkami, zamiast konstruowania każdej umowy od zera - to warunek skalowania tej ścieżki poza jedną osobę.</li>
              <li>Wykorzystać referencje z bazy (ElevenLabs, ICEYE)<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="319">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup> jako dowód jakości środowiska, w które wchodzi partner korporacyjny.</li>
            </ul>
            <p class="note" style="margin:2px 0 0">Pomiar: liczba i wartość umów partnerskich, średnia wartość kontraktu, udział przychodu z partnerstw w całości, liczba spotkań na poziomie decyzyjnym.</p>
          </div>
        ` },
        { id: 'wz-3', label: "Onboarding i retencja", html: `
          <p class="axis-intro">Diagnoza: obszar o najlepszym stosunku efektu do nakładu. W organizacjach członkowskich retencja pierwszoroczna wynosi 74-75%, a 52% nieodnowień wynika z braku zaangażowania, nie z ceny<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="320">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup>. Oferta wprost wymienia wdrażanie działań retencyjnych jako obowiązek na stanowisku<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="321">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>.</p>
          <div class="card">
            <div class="matters-title">Co bym zrobił</div>
            <ul class="matters">
              <li>Wprowadzić ustrukturyzowany onboarding nowego członka: powitanie w ciągu 48 godzin, rozmowa wprowadzająca w pierwszym miesiącu, przypisanie do co najmniej jednej grupy roboczej lub webinaru w pierwszym kwartale.</li>
              <li>Zdefiniować i mierzyć wskaźnik zaangażowania jako sygnał wyprzedzający odejście: udział w webinarach, wydarzeniach i grupach roboczych; brak aktywności przez określony czas uruchamia kontakt.</li>
              <li>Zbudować kalendarz powtarzalnych powodów kontaktu w oparciu o to, co izba już produkuje: aktualizacje regulacyjne, cykl „EU AI Act Essentials”, raporty i spotkania społeczności<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 18, 11 — pokaż źródło" data-refs="18,11" data-fn="322">18,11<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em><br><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em></span></sup>.</li>
              <li>Wykorzystać terminy AI Act jako naturalny rytm komunikacji - obowiązki transparentności od sierpnia 2026 i systemy wysokiego ryzyka od grudnia 2027<sup class="fn" tabindex="0" role="button" aria-label="Przypis 3, 4 — pokaż źródło" data-refs="3,4" data-fn="323">3,4<span class="fc" role="note"><b>3.</b> Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2024/1689 z dnia 13 czerwca 2024 r. ustanawiające zharmonizowane przepisy dotyczące sztucznej inteligencji (akt w sprawie sztucznej inteligencji), Dziennik Urzędowy Unii Europejskiej, seria L, 2024/1689. <em>M1</em><br><b>4.</b> Komisja Europejska, pakiet Digital Omnibus - propozycja uproszczenia przepisów cyfrowych i przesunięcia terminów stosowania obowiązków, listopad 2025 r. <em>M1</em></span></sup> dają konkretne, datowane powody kontaktu z każdym członkiem.</li>
              <li>Zaplanować kampanię utrzymaniową pod termin wypowiedzenia: skoro członkostwo odnawia się automatycznie przy braku wypowiedzenia do 31 grudnia<sup class="fn" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="324">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup>, czwarty kwartał jest najważniejszym okresem roku dla retencji i naturalnym momentem rozmów o wyższym pakiecie.</li>
              <li>Wprowadzić rozmowę wyjściową z każdym rezygnującym członkiem i rejestrować przyczyny - to najtańsze źródło wiedzy o produkcie.</li>
            </ul>
            <p class="note" style="margin:2px 0 0">Pomiar: wskaźnik odnowień ogólny i osobno pierwszoroczny, udział członków aktywnych, liczba rezygnacji z podaną przyczyną, konwersja na wyższy pakiet.</p>
          </div>
        ` },
        { id: 'wz-4', label: "Ekspansja regionalna", html: `
          <p class="axis-intro">Diagnoza: narracja izby jest regionalna<sup class="fn" tabindex="0" role="button" aria-label="Przypis 6 — pokaż źródło" data-refs="6" data-fn="325">6<span class="fc" role="note"><b>6.</b> AI Chamber, „About Us”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>, baza w praktyce polska. Sześć z dziewięciu krajów ma reprezentację symboliczną<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="326">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, przy czym Czechy są jednocześnie pierwotnym celem ekspansji deklarowanym przez CEO<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 26 — pokaż źródło" data-refs="26" data-fn="327">26<span class="fc" role="note"><b>26.</b> Sifted, materiał o inauguracji AI Chamber, 24 kwietnia 2024 r. - baza startowa blisko 50 firm, deklaracja czterokrotnego wzrostu w ciągu roku, Czechy jako pierwszy cel ekspansji. <em>M2</em></span></sup>, gospodarzem szczytu 2026<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="328">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup> i rynkiem o obecności śladowej.</p>
          <div class="card">
            <div class="matters-title">Co bym zrobił</div>
            <ul class="matters">
              <li>Wybrać jeden rynek priorytetowy zamiast rozpraszać wysiłek na sześć: Czechy, ze względu na szczyt w Pradze, zaplecze w osobie byłego rządowego komisarza do spraw AI w radzie doradczej oraz auspicje czeskiego ministerstwa nad wydarzeniem.</li>
              <li>Przygotować kampanię akwizycyjną skorelowaną ze szczytem: pozyskiwanie czeskich firm w okresie poprzedzającym wydarzenie, z udziałem w szczycie jako częścią propozycji wartości.</li>
              <li>Wykorzystać koalicję trzynastu organizacji z listu otwartego w sprawie Digital Omnibus<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 17 — pokaż źródło" data-refs="17" data-fn="329">17<span class="fc" role="note"><b>17.</b> AI Chamber wraz z dwunastoma innymi organizacjami regionu, list otwarty w sprawie pakietu Digital Omnibus, grudzień 2025 r. <em>M1</em></span></sup> jako sieć wejść na kolejne rynki - są to podmioty, z którymi izba już współpracowała.</li>
              <li>Zbudować lokalny argument obok unijnego: wartość advocacy jest odczuwalna przede wszystkim krajowo, więc na każdym rynku potrzebny jest konkretny przykład sprawy prowadzonej lokalnie.</li>
              <li>Rozważyć formułę lokalnego ambasadora lub przedstawiciela w kraju docelowym zamiast sprzedaży wyłącznie zdalnej - w modelu relacyjnym obecność lokalna istotnie skraca cykl.</li>
              <li>Zaadresować dwa segmenty nieobecne w bazie: fundusze VC i uczelnie<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="330">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>. Punkt zaczepienia już istnieje w radzie doradczej (Akademia Leona Koźmińskiego, PAN, board EIT)<sup class="fn" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="331">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>, a filar finansowania z CEE AI Action Plan<sup class="fn" tabindex="0" role="button" aria-label="Przypis 13 — pokaż źródło" data-refs="13" data-fn="332">13<span class="fc" role="note"><b>13.</b> AI Chamber, „CEE AI Action Plan”, dokument programowy zaprezentowany w Gdańsku podczas prezydencji Polski w Radzie Unii Europejskiej, 2025 r. - pięć filarów oraz dane o adopcji AI w regionie na poziomie 4-6%. <em>M1</em></span></sup> daje merytoryczny pretekst do rozmowy z funduszami.</li>
            </ul>
            <p class="note" style="margin:2px 0 0">Pomiar: liczba członków spoza Polski, udział rynków zagranicznych w nowych przystąpieniach, liczba nowych segmentów instytucjonalnych w bazie.</p>
          </div>
        ` },
        { id: 'wz-5', label: "Wydarzenia jako lejek", html: `
          <p class="axis-intro">Diagnoza: portfel wydarzeń jest zróżnicowany i obejmuje szczyt regionalny, debaty oksfordzkie, spotkania społeczności i webinary<sup class="fn" tabindex="0" role="button" aria-label="Przypis 16, 18 — pokaż źródło" data-refs="16,18" data-fn="333">16,18<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em><br><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>. Ogłoszenie wprost wymienia wspieranie lead generation i networkingu podczas wydarzeń<sup class="fn" tabindex="0" role="button" aria-label="Przypis 19 — pokaż źródło" data-refs="19" data-fn="334">19<span class="fc" role="note"><b>19.</b> „Partnerships &amp; Membership Growth Manager”, ogłoszenie rekrutacyjne AI Chamber, 2026 r. - zakres obowiązków, wymagania, warunki współpracy oraz wymagania dodane przez publikującego ofertę. <em>M1</em></span></sup>, ale nie ustalono, czy istnieje proces przekazywania kontaktów z wydarzenia do pipeline'u.</p>
          <div class="card">
            <div class="matters-title">Co bym zrobił</div>
            <ul class="matters">
              <li>Zaprojektować pełną ścieżkę wokół każdego wydarzenia: lista docelowa przed, plan rozmów w trakcie, kontakt następczy w ciągu 72 godzin, przypisanie kontaktu do etapu w CRM.</li>
              <li>Traktować CEE AI Summit 2026 w Pradze jako projekt sprzedażowy z własnym celem liczbowym, a nie wyłącznie jako wydarzenie wizerunkowe - to najbliższy duży termin po zatrudnieniu.</li>
              <li>Wykorzystać formaty kameralne (AI Chamber Hangout<sup class="fn" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="335">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>, roundtables z pakietu Premium Connections<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 11 — pokaż źródło" data-refs="11" data-fn="336">11<span class="fc" role="note"><b>11.</b> AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em></span></sup>) jako narzędzie akwizycyjne dla wąskich grup decydentów - w sprzedaży członkostwa kameralne działa lepiej niż masowe.</li>
              <li>Wykorzystać webinary jako mechanizm kwalifikacji: uczestnik cyklu „EU AI Act Essentials”<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="337">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup> sam wskazuje swój problem regulacyjny, co daje naturalny punkt startu rozmowy.</li>
              <li>Zbudować powtarzalny format spotkań na rynkach zagranicznych, powiązany z premierami publikacji izby, wzorem wydarzenia brukselskiego z NCBR<sup class="fn" tabindex="0" role="button" aria-label="Przypis 18 — pokaż źródło" data-refs="18" data-fn="338">18<span class="fc" role="note"><b>18.</b> AI Chamber, działy „News” i „Events”, aichamber.eu, dostęp: sierpień 2026 - wydarzenie w Brukseli z Narodowym Centrum Badań i Rozwoju (lipiec 2025), debaty oksfordzkie, AI Chamber Hangout, cykl webinarów „EU AI Act Essentials”, stanowiska konsultacyjne. <em>M1</em></span></sup>.</li>
              <li>Mierzyć każde wydarzenie osobno: koszt na pozyskany kontakt oraz konwersję kontakt - rozmowa - członek, żeby po roku wiedzieć, które formaty naprawdę sprzedają.</li>
            </ul>
            <p class="note" style="margin:2px 0 0">Pomiar: liczba kontaktów z wydarzenia, konwersja na rozmowę i na członkostwo, koszt pozyskania kontaktu, liczba domkniętych partnerstw powiązanych z wydarzeniem.</p>
          </div>
        ` },
      ],
    },
    { kind: 'html', html: `<div class="verdict block" style="margin-top:22px">
        <h4>Kolejność wdrożenia</h4>
        <p>Plan nie zakłada realizacji pięciu obszarów jednocześnie. Kolejność wynika ze stosunku efektu do czasu: najpierw akwizycja i pipeline, bo bez ustandaryzowanego procesu każdy kolejny obszar opiera się na przypadku; równolegle onboarding i retencja, bo to najtańszy wzrost netto i element wprost wskazany w ofercie; następnie partnerstwa korporacyjne i wydarzenia, skorelowane ze szczytem w Pradze we wrześniu; na końcu ekspansja regionalna, która wymaga zbudowanej wcześniej maszyny. Całość jest hipotezą opartą na danych publicznych - pierwszym krokiem po zatrudnieniu powinna być jej weryfikacja wobec danych wewnętrznych izby, w szczególności rzeczywistego wskaźnika odnowień i struktury źródeł leadów.</p>
      </div>` },
  ],
};
