import type { DossierPage } from './types';

export const pagePitch: DossierPage = {
  id: 'pitch',
  num: '15',
  navLabel: "Elevator pitch",
  group: "Podsumowanie",
  eyebrow: "15 · Podsumowanie",
  title: `Elevator pitch - dlaczego ja w 60 sekund`,
  lead: `Cztery warianty krótkiej autoprezentacji plus zestaw gotowych zdań. Wariant dobiera się do rozmówcy i momentu rozmowy - nie ma jednej wersji na wszystko. Odsyłacze przy liczbach wskazują źródło każdej danej wypowiadanej na głos<sup class="fn" tabindex="0" role="button" aria-label="Przypis 12, 14, 34 — pokaż źródło" data-refs="12,14,34" data-fn="339">12,14,34<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em><br><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em><br><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup>.`,
  blocks: [
    { kind: 'html', html: `<div class="card">
        <h4>Wariant A - budowniczy relacji z policzalnym wynikiem <span class="pill cyan">~60 s</span></h4>
        <p class="note" style="margin:2px 0 8px">Kiedy: wersja bazowa, gdy rozmówca ocenia dopasowanie do roli sprzedażowej.</p>
        <p>Od siedmiu lat robię w istocie jedną rzecz: przekonuję organizację albo człowieka o wysokiej pozycji, żeby wszedł w relację, a potem tę relację utrzymuję. W European Financial Congress pozyskałem czternastu sponsorów oraz partnerów medialnych i honorowych<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="340">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup>. Prowadząc własny think tank, zbudowałem sieć ponad stu współpracowników, analityków i członków rad programowych<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="341">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup> - a to jest trudniejsza sprzedaż niż składka członkowska, bo ludzie oddawali swój czas i nazwisko, nie budżet firmy. Przy trzech edycjach własnej konferencji pozyskałem dwudziestu pięciu partnerów<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="342">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup>. Nie miałem stanowiska nazwanego business development, ale wykonywałem dokładnie te czynności, które opisuje Państwa ogłoszenie, i mam z nich policzalne wyniki. W tej roli chcę je powtórzyć na produkcie, który rozumiem, bo sam projektowałem i wyceniałem ofertę organizacji członkowskiej.</p>
      </div>
<div class="card" style="margin-top:14px">
        <h4>Wariant B - dopasowanie do AI Chamber <span class="pill cyan">~60 s</span></h4>
        <p class="note" style="margin:2px 0 8px">Kiedy: gdy pytają o motywację i dopasowanie, czyli „dlaczego my”.</p>
        <p>AI, technologia i polityka publiczna to nie są dla mnie hasła z ogłoszenia - prowadzę think tank zajmujący się geopolityką i technologią, a AI Act i pozycja regulacyjna Europy Środkowo-Wschodniej to tematy, którymi zajmuję się poza pracą. Oznacza to, że rozmowa z potencjalnym członkiem o tym, dlaczego warto mieć wpływ na kształt regulacji, nie będzie dla mnie odtwarzaniem cudzych argumentów. Państwa organizacja jest w fazie, w której pracuję najlepiej: około dziewięćdziesięciu członków<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="343">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, silne aktywa w postaci rady doradczej<sup class="fn" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="344">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup> i własnych badań<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 14 — pokaż źródło" data-refs="14" data-fn="345">14<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em></span></sup>, ale bez ustandaryzowanego procesu sprzedaży<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 10 — pokaż źródło" data-refs="10" data-fn="346">10<span class="fc" role="note"><b>10.</b> AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em></span></sup> - a odpowiedniki z Niemiec i Francji pokazują, że bazy pięciuset i ośmiuset podmiotów są osiągalne<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 23, 24 — pokaż źródło" data-refs="23,24" data-fn="347">23,24<span class="fc" role="note"><b>23.</b> KI Bundesverband, informacja o liczbie członków (ponad 500), ki-verband.de, dostęp: sierpień 2026. <em>M2</em><br><b>24.</b> Hub France IA, informacja o liczbie członków i partnerów (ponad 800, w tym ponad 200 organizacji, ponad 160 startupów i ponad 50 partnerów europejskich), hub-franceia.fr, dostęp: sierpień 2026. <em>M2</em></span></sup>. Chcę budować ten proces, a nie tylko go obsługiwać.</p>
      </div>
<div class="card" style="margin-top:14px">
        <h4>Wariant C - wdrożeniowy, od razu do rzeczy <span class="pill cyan">~60 s</span></h4>
        <p class="note" style="margin:2px 0 8px">Kiedy: gdy chcą zobaczyć konkret i sposób działania, nie deklaracje.</p>
        <p>Nie zaczynam od deklaracji, tylko od diagnozy. Przeanalizowałem Państwa bazę: około dziewięćdziesięciu firm z dziewięciu krajów, ale w sześciu z nich reprezentacja jest symboliczna<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 12 — pokaż źródło" data-refs="12" data-fn="348">12<span class="fc" role="note"><b>12.</b> AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em></span></sup>, mimo że narracja izby jest regionalna<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 6 — pokaż źródło" data-refs="6" data-fn="349">6<span class="fc" role="note"><b>6.</b> AI Chamber, „About Us”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>. Nie ma na liście funduszy VC ani uczelni, choć w radzie doradczej są już Akademia Leona Koźmińskiego, PAN i board EIT<sup class="fn" tabindex="0" role="button" aria-label="Przypis 9 — pokaż źródło" data-refs="9" data-fn="350">9<span class="fc" role="note"><b>9.</b> AI Chamber, „Board of Advisors”, aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>. W pierwszych dziewięćdziesięciu dniach zrobiłbym analizę tego, skąd przyszli dotychczasowi członkowie, uporządkował etapy w CRM, zbudował materiał sprzedażowy oparty na Państwa własnym raporcie z jedenastu krajów<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 14 — pokaż źródło" data-refs="14" data-fn="351">14<span class="fc" role="note"><b>14.</b> AI Chamber, „How do SMEs in CEE find their way in the world of AI?”, raport z badania ponad 3 200 pracowników z 11 krajów, lipiec 2025 r. <em>M1</em></span></sup> i przygotował kampanię pod szczyt w Pradze trzeciego września<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 16 — pokaż źródło" data-refs="16" data-fn="352">16<span class="fc" role="note"><b>16.</b> AI Chamber, zapowiedź „CEE AI Summit 2026”, Praga, Martinic Palace, 3 września 2026 r., pod auspicjami Ministerstwa Przemysłu i Handlu Republiki Czeskiej; aichamber.eu, dostęp: sierpień 2026. <em>M1</em></span></sup>. Równolegle wprowadziłbym onboarding nowego członka, bo w organizacjach członkowskich co czwarty nowy członek odpada przed drugą składką, a ponad połowa odejść wynika z braku zaangażowania, nie z ceny<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="353">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup>. To najtańszy wzrost, jaki mogę Państwu dać w pierwszym roku.</p>
      </div>
<div class="card" style="margin-top:14px">
        <h4>Wariant D - krótki <span class="pill cyan">~30 s</span></h4>
        <p class="note" style="margin:2px 0 8px">Kiedy: szybkie przedstawienie na start lub przy ograniczonym czasie.</p>
        <p>Zajmuję się pozyskiwaniem organizacji i ludzi do wspólnych przedsięwzięć: czternastu partnerów kongresu EFC, dwudziestu pięciu partnerów własnej konferencji, ponad stu współpracowników think tanku, który założyłem<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="354">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup>. Warsztat analityczny mam z rynku finansowego, więc o wartości współpracy rozmawiam na liczbach. AI i polityka publiczna to mój obszar zawodowy także poza pracą - w tej roli nie musiałbym uczyć się tematu, tylko od razu rozmawiać z klientem na jego poziomie.</p>
      </div>
<div class="card" style="margin-top:14px">
        <h4>Kluczowe zdania (haczyki do wplecenia)</h4>
        <ul class="matters">
          <li>Nie miałem stanowiska nazwanego sprzedażą, ale mam liczby: czternastu partnerów kongresu, dwudziestu pięciu partnerów konferencji, ponad stu współpracowników fundacji<sup class="fn" tabindex="0" role="button" aria-label="Przypis 34 — pokaż źródło" data-refs="34" data-fn="355">34<span class="fc" role="note"><b>34.</b> Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></sup>.</li>
          <li>Znam ten produkt z drugiej strony stołu - sam projektowałem i wyceniałem ofertę organizacji członkowskiej.</li>
          <li>Sprzedaż członkostwa bez onboardingu jest sprzedażą jednorazową: co czwarty nowy członek odpada przed drugą składką<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 22 — pokaż źródło" data-refs="22" data-fn="356">22<span class="fc" role="note"><b>22.</b> Marketing General Incorporated, „2025 Membership Marketing Benchmarking Report”, 2025 r. - mediana odnowień 84%, organizacje branżowe 85-89%, retencja pierwszoroczna 74-75%, 52% nieodnowień z powodu braku zaangażowania; dane dotyczą rynku amerykańskiego. <em>M2</em></span></sup>.</li>
          <li>Firma o dwudziestu pracownikach nie wpłynie sama na regulację unijną. Koalicja trzynastu organizacji już to robiła<sup class="fn r" tabindex="0" role="button" aria-label="Przypis 17 — pokaż źródło" data-refs="17" data-fn="357">17<span class="fc" role="note"><b>17.</b> AI Chamber wraz z dwunastoma innymi organizacjami regionu, list otwarty w sprawie pakietu Digital Omnibus, grudzień 2025 r. <em>M1</em></span></sup>.</li>
          <li>Nie mam sieci w Czechach i nie będę tego udawać - mam metodę jej zbudowania, a pierwszym testem byłby wrzesień w Pradze.</li>
          <li>Wchodzę do rozmowy z danymi o rynku klienta, nie z prezentacją o izbie.</li>
        </ul>
      </div>
<div class="verdict cyan block" style="margin-top:20px">
        <h4>Jak tego użyć</h4>
        <p>Warto opanować jedną wersję na pamięć - rekomendacja: wariant A jako bazowy, bo od razu adresuje najbardziej prawdopodobne zastrzeżenie dotyczące braku formalnego stażu sprzedażowego - i mieć pozostałe jako moduły do podmiany zależnie od pytania. Wariant B, gdy pytają o motywację; wariant C, gdy chcą konkretu i planu; wariant D na szybkie przedstawienie. Zdania-haczyki działają też pojedynczo, jako mocne domknięcie odpowiedzi w dowolnym momencie rozmowy. Jedna zasada obowiązuje we wszystkich wariantach: nie ukrywać luki w doświadczeniu sprzedażowym, tylko wyprzedzać ją liczbami - kandydat, który sam nazywa swoją słabość i natychmiast pokazuje, czym ją równoważy, wypada wiarygodniej niż ten, który czeka, aż rozmówca to wychwyci.</p>
      </div>` },
  ],
};
