import { SEO_PAGES } from './pages-seo';
import { TRAFFIC_PAGES } from './pages-traffic';
import type { DossierBlock, DossierPage } from './types';

/**
 * Hand-written additions and corrections layered on top of the generated pages.
 *
 * `01-*.ts` … `15-*.ts` and `index.ts` are regenerated by
 * `scripts/import-dossier.mjs` and lose anything edited into them. Content that
 * did not come from the source document therefore lives here — this file is
 * never touched by the importer.
 *
 * Two kinds of change are supported:
 *  - `DOSSIER_OVERLAYS` splice whole blocks into a page,
 *  - `DOSSIER_PATCHES` replace an exact fragment of generated markup, for facts
 *    the source document stated before newer primary sources contradicted them.
 *
 * Every patch records why it exists, so a reviewer can tell a correction from a
 * rewrite. A patch that stops matching after a regeneration fails loudly in dev.
 */

/** `at` is the block index to splice at; omit it to append. */
export interface DossierOverlay {
  pageId: string;
  at?: number;
  blocks: DossierBlock[];
}

export interface DossierPatch {
  pageId: string;
  /** Exact fragment of the generated markup (lead or block HTML). */
  find: string;
  replace: string;
  /** Expected number of occurrences; defaults to 1. */
  count?: number;
  /** Why the original no longer holds. Not rendered — for reviewers. */
  reason: string;
}

/* ------------------------------------------------------------------ *
 * Footnote helper — matches the markup the importer emits, so ported   *
 * and hand-written references look and behave identically.             *
 * ------------------------------------------------------------------ */
const FN_SOURCES: Record<string, string> = {
  '10': 'AI Chamber, „How to become a member of the AI Chamber?”, aichamber.eu, dostęp: sierpień 2026 - pakiety BASIC, PRO i PREMIUM, mechanika składki, opłata rejestracyjna oraz termin wypowiedzenia 31 grudnia. <em>M1</em>',
  '11': 'AI Chamber, „Cooperation - Corporate Partnerships”, aichamber.eu, dostęp: sierpień 2026 - filary Strategic Insights, Premium Connections, Business Growth i Market Visibility oraz adres kontaktowy. <em>M1</em>',
  '12': 'AI Chamber, „Members”, aichamber.eu, dostęp: sierpień 2026 - publiczna lista firm członkowskich; liczba około 90 pochodzi ze zliczenia własnego. <em>M1</em>',
  '33': 'RocketReach, szacunkowa wielkość zespołu AI Chamber (około 12 osób) oraz część nazwisk niepotwierdzonych na stronie „Meet The Team”; dostęp: sierpień 2026. <em>M4</em>',
  '35': 'AI Chamber, „Membership Application” - formularz członkowski, 2026 r. - jednorazowa opłata rejestracyjna 20 EUR oraz składki roczne BASIC 150 EUR, PRO 500 EUR i PREMIUM 1 500 EUR; wybór waluty PLN albo EUR; progi zatrudnienia 1-5, 6-50, 51-250 i powyżej 250 osób. <em>M1</em>',
  '36': 'Statut „AI Chamber”, wersja angielska, 2026 r. - art. 1 (podstawa prawna: ustawa z 30 maja 1989 r. o izbach gospodarczych), art. 3 ust. 2, art. 7-9, art. 11 pkt 11, art. 21 oraz art. 22. <em>M1</em>',
};

let fnSeq = 900;

/** Renders a footnote reference identical in structure to the generated ones. */
function fn(refs: string, variant = ''): string {
  const list = refs.split(',').map((r) => r.trim());
  const cls = ['fn', variant].filter(Boolean).join(' ');
  const body = list.map((n) => `<b>${n}.</b> ${FN_SOURCES[n]}`).join('<br>');
  fnSeq += 1;
  return (
    `<sup class="${cls}" tabindex="0" role="button"` +
    ` aria-label="Przypis ${list.join(', ')} — pokaż źródło"` +
    ` data-refs="${list.join(',')}" data-fn="${fnSeq}">${list.join(',')}` +
    `<span class="fc" role="note">${body}</span></sup>`
  );
}

/* ------------------------------------------------------------------ *
 * 04 · Model przychodowy — cennik składek                              *
 * ------------------------------------------------------------------ */

const PRICING_METRICS: DossierBlock = {
  kind: 'html',
  html: `<div class="metrics c4 block">
  <div class="metric amber"><div class="n">20<small> EUR</small></div><div class="l">jednorazowa opłata rejestracyjna${fn('35')}</div></div>
  <div class="metric"><div class="n">150<small> EUR</small></div><div class="l">BASIC - składka roczna, do 5 pracowników${fn('35')}</div></div>
  <div class="metric"><div class="n">500<small> EUR</small></div><div class="l">PRO - składka roczna, 6-50 pracowników${fn('35')}</div></div>
  <div class="metric cyan"><div class="n">1 500<small> EUR</small></div><div class="l">PREMIUM - składka roczna, 51-250 pracowników${fn('35', 'r')}</div></div>
</div>`,
};

const PRICING_ANALYSIS: DossierBlock = {
  kind: 'html',
  html: `<div class="card block"><h3>Cennik składek${fn('35')} <span class="mono">stawki jawne</span></h3>
  <p>Formularz członkowski podaje stawki wprost, razem z jednorazową opłatą rejestracyjną i wyborem waluty. Zamyka to lukę wskazaną w pierwotnym rozpoznaniu, w którym wysokość składki uznano za niejawną do momentu otrzymania deklaracji${fn('10')}. Pakiet wyznacza liczba pracowników, ale mniejsza firma może wybrać wyższy poziom, jeśli zależy jej na szerszym zakresie korzyści; zmiana pakietu w trakcie roku wymaga zgody zarządu i zaktualizowanego wniosku${fn('10', 'r')}.</p>
  <div class="matters-title">Co z tych liczb wynika</div>
  <ul class="matters">
    <li>Rozpiętość między najniższym a najwyższym pakietem jest dziesięciokrotna. Jeden pozyskany PREMIUM równa się dziesięciu firmom w BASIC przy porównywalnym nakładzie na rozmowę. <span class="v">10×</span></li>
    <li>Opłata rejestracyjna nie jest strumieniem przychodu - przy całej obecnej bazie dałaby około 1,8 tys. EUR jednorazowo. Pełni funkcję filtra zaangażowania i momentu wystawienia faktury VAT. <span class="v">20 EUR</span></li>
    <li>Cały przychód ze składek przy bazie około 90 firm${fn('12')} mieści się w przedziale od 13,5 tys. EUR (gdyby wszystkie firmy były w BASIC) do 135 tys. EUR (gdyby wszystkie były w PREMIUM). <span class="v">13,5-135 tys. EUR</span></li>
    <li>Nawet górny kraniec tego przedziału nie pokrywa kosztów zespołu szacowanego na kilkanaście osób${fn('33', 'r')}. Składki są więc produktem wejściowym i dowodem trakcji, a nie filarem finansowania izby. <span class="v">wniosek M5</span></li>
    <li>Składkę można rozliczać w złotych albo w euro, co przy członkach spoza Polski zdejmuje barierę walutową, ale przenosi ryzyko kursowe na izbę. <span class="v">PLN / EUR</span></li>
  </ul>
  <p class="note">Przedział 13,5-135 tys. EUR to wyliczenie własne: liczba członków ze zliczenia publicznej listy pomnożona przez skrajne stawki z formularza. Nie jest prognozą przychodu - rzeczywista wartość zależy od struktury pakietów w bazie, która nie jest jawna. To jedyna luka, jaka w tym obszarze pozostała po ujawnieniu cennika.</p>
</div>`,
};

const STATUTE_RULES: DossierBlock = {
  kind: 'html',
  html: `<div class="card block"><h3>Reguły składkowe w statucie${fn('36')} <span class="mono">art. 3, 7-9, 11, 21 i 22</span></h3>
  <p>Cennik mówi, ile kosztuje członkostwo. Statut mówi, kto te stawki ustala, w jakim terminie trzeba zapłacić i co się dzieje przy zaległości - czyli to, co w rozmowie o odnowieniu decyduje o realnym polu manewru.</p>
  <table class="data" style="margin-top:12px">
    <thead><tr><th>Zagadnienie</th><th>Podstawa</th><th>Treść</th></tr></thead>
    <tbody>
      <tr><td>Kto ustala stawki</td><td class="num tabnum">art. 11 pkt 11, art. 22 ust. 1</td><td>Walne Zgromadzenie Członków, corocznie z góry do 31 grudnia; może różnicować poziomy według kategorii członkostwa. Brak uchwały oznacza, że obowiązuje stawka z roku poprzedniego.</td></tr>
      <tr><td>Termin pierwszej płatności</td><td class="num tabnum">art. 22 ust. 2</td><td>Z góry, jednorazowo za 12 miesięcy liczonych od przystąpienia, w ciągu 30 dni od wystawienia dokumentu księgowego i przyjęcia w poczet członków.</td></tr>
      <tr><td>Kolejne lata</td><td class="num tabnum">art. 22 ust. 2</td><td>30 dni od rocznicy członkostwa, czyli od daty przystąpienia - chyba że zarząd postanowi inaczej.</td></tr>
      <tr><td>Zaległość</td><td class="num tabnum">art. 9 ust. 2</td><td>Wezwanie do zapłaty, po co najmniej 7 dniach drugie wezwanie, po kolejnych 7 dniach zawieszenie praw członka do czasu pełnej spłaty.</td></tr>
      <tr><td>Wykluczenie</td><td class="num tabnum">art. 9 ust. 1 lit. d</td><td>Zaleganie ze składką dłużej niż sześć miesięcy jest samodzielną podstawą uchwały o wykluczeniu.</td></tr>
      <tr><td>Zakres korzyści</td><td class="num tabnum">art. 7 ust. 1 lit. b</td><td>Udział w działalności izby może być ograniczony wysokością opłaconej składki - to statutowa podstawa różnicowania pakietów.</td></tr>
      <tr><td>Przyjęcie członka</td><td class="num tabnum">art. 8</td><td>Decyduje zarząd po rozpatrzeniu wniosku; deklaracja zawiera zobowiązanie do opłaty wpisowej.</td></tr>
      <tr><td>Źródła przychodu izby</td><td class="num tabnum">art. 21</td><td>Działalność statutowa i gospodarcza, składki, dochód z majątku, dotacje i subwencje, odsetki, spadki, darowizny i zapisy.</td></tr>
      <tr><td>Przeznaczenie zysku</td><td class="num tabnum">art. 3 ust. 2</td><td>Dochód z działalności gospodarczej służy celom statutowym i nie może być dzielony między członków.</td></tr>
    </tbody>
  </table>
  <div class="matters-title" style="margin-top:14px">Rozbieżność warta zapamiętania</div>
  <ul class="matters">
    <li>Komunikacja na stronie wiąże składkę z rokiem kalendarzowym: naliczenie proporcjonalne od miesiąca płatności i automatyczne odnowienie przy braku wypowiedzenia do 31 grudnia${fn('10')}. Statut wiąże płatność z rocznicą przystąpienia${fn('36', 'r')}. <span class="v">31.12 vs rocznica</span></li>
    <li>Praktyczna konsekwencja: ryzyko rezygnacji kumuluje się w grudniu, ale fakturowanie rozkłada się na cały rok według dat przystąpienia. Kampania utrzymaniowa i kalendarz gotówkowy to dwa różne harmonogramy, których nie należy mylić.</li>
    <li>To także gotowe pytanie na rozmowę: który z tych dwóch kalendarzy obowiązuje w praktyce i czy zarząd korzystał z zastrzeżenia „chyba że zarząd postanowi inaczej”.</li>
  </ul>
</div>`,
};

const PRICING_VERDICT: DossierBlock = {
  kind: 'html',
  html: `<div class="verdict cyan block"><h4>Co cennik zmienia w ocenie roli</h4><p>Ujawnienie stawek przesuwa punkt ciężkości z pozyskiwania liczby członków na ich strukturę: przy rozpiętości 150-1 500 EUR jeden PREMIUM wart jest dziesięciu firm w BASIC, a nakład na rozmowę jest podobny. Jednocześnie nawet komplet obecnej bazy w najwyższym pakiecie daje około 135 tys. EUR rocznie, czyli mniej niż koszt kilkunastoosobowego zespołu - składki są dowodem trakcji i produktem wejściowym, a nie filarem finansowania. Realny wynik roli rozstrzyga się więc po stronie partnerstw korporacyjnych i sponsoringu, których cennik pozostaje niejawny${fn('11')}. Statutowa ścieżka zaległości - dwa wezwania, zawieszenie praw, wykluczenie po sześciu miesiącach${fn('36', 'r')} - daje twarde narzędzie windykacyjne, ale pokazuje też, że retencja jest w tej organizacji procesem operacyjnym, nie wyłącznie relacyjnym.</p></div>`,
};

/* ------------------------------------------------------------------ *
 * 08 · Źródła — nowe pozycje bibliograficzne                           *
 * ------------------------------------------------------------------ */

const ENTRY_34 =
  '<div class="i" id="zrodlo-34" data-src="34"><span class="n">34.</span><span class="t">Igor Miasnikow, CV oraz portfolio projektów - dane własne kandydata, 2026 r. <em>M1</em></span></div>';

const NEW_ENTRIES = `${ENTRY_34}
          <span class="g">Dokumenty członkowskie i korporacyjne</span>
          <div class="i" id="zrodlo-35" data-src="35"><span class="n">35.</span><span class="t">AI Chamber, „Membership Application” - formularz członkowski, 2026 r. - jednorazowa opłata rejestracyjna 20 EUR oraz składki roczne BASIC 150 EUR, PRO 500 EUR i PREMIUM 1 500 EUR; wybór waluty PLN albo EUR; progi zatrudnienia 1-5, 6-50, 51-250 i powyżej 250 osób. <em>M1</em></span></div>
          <div class="i" id="zrodlo-36" data-src="36"><span class="n">36.</span><span class="t">Statut „AI Chamber”, wersja angielska, 2026 r. - art. 1 (podstawa prawna: ustawa z 30 maja 1989 r. o izbach gospodarczych), art. 3 ust. 2, art. 7-9, art. 11 pkt 11, art. 21 oraz art. 22. <em>M1</em></span></div>
          <span class="g">Dane o ruchu w sieci</span>
          <div class="i" id="zrodlo-37" data-src="37"><span class="n">37.</span><span class="t">SimilarWeb, „Website Analysis: aichamber.eu”, raport za okres marzec-sierpień 2026, odczyt 16 września 2026 r. - ruch, zaangażowanie, kanały pozyskania, geografia i wyszukiwarka. <em>M2</em></span></div>
          <div class="i" id="zrodlo-38" data-src="38"><span class="n">38.</span><span class="t">SimilarWeb, „Website Analysis: ceeaisummit.eu”, raport za okres marzec-sierpień 2026, odczyt 16 września 2026 r. - ruch, zaangażowanie, kanały pozyskania, geografia i wyszukiwarka. <em>M2</em></span></div>
          <div class="i" id="zrodlo-39" data-src="39"><span class="n">39.</span><span class="t">ceeaisummit.eu, zapowiedź prelegentów CEE AI Summit 2026 - odczyt z podglądu strony zamieszczonego w raporcie SimilarWeb, sierpień 2026 r. <em>M2</em></span></div>
          <span class="g">Widoczność w wyszukiwarce</span>
          <div class="i" id="zrodlo-40" data-src="40"><span class="n">40.</span><span class="t">Semrush, „Linki zwrotne: Przegląd”, aichamber.eu, domena główna, eksport z 16 września 2026 r. - Authority Score, domeny odsyłające, atrybuty i typy linków, rozkład Authority Score domen odsyłających, rozkład końcówek domen, kraje oraz anchory z datami pierwszego i ostatniego wystąpienia. <em>M2</em></span></div>
          <div class="i" id="zrodlo-41" data-src="41"><span class="n">41.</span><span class="t">Semrush, „Lista linków zwrotnych”, aichamber.eu, eksport stu pozycji z 16 września 2026 r. - adresy stron linkujących, anchory, atrybuty i Authority Score poszczególnych podstron. <em>M2</em></span></div>
          <div class="i" id="zrodlo-42" data-src="42"><span class="n">42.</span><span class="t">Semrush, „Pozycje organiczne”, aichamber.eu, baza danych Polska, odczyt panelu z 16 września 2026 r. - siedem fraz z pozycją, wolumeny, trudność i adresy docelowe. <em>M2</em></span></div>
          <div class="i" id="zrodlo-43" data-src="43"><span class="n">43.</span><span class="t">Answer the Public, prompty AI dla aichamber.eu, język polski, Polska, eksport z 16 września 2026 r. - dwadzieścia pięć zapytań przypisanych do ChatGPT i Gemini wraz z klasyfikacją intencji. <em>M2</em></span></div>`;

/* ------------------------------------------------------------------ */

export const DOSSIER_OVERLAYS: DossierOverlay[] = [
  {
    pageId: 'model',
    // after the member-base chart, before the reconstructed revenue architecture
    at: 1,
    blocks: [PRICING_METRICS, PRICING_ANALYSIS, STATUTE_RULES, PRICING_VERDICT],
  },
];

export const DOSSIER_PATCHES: DossierPatch[] = [
  /* --- prices are public now: the source document assumed they were not --- */
  {
    pageId: 'model',
    find: 'Izba nie publikuje sprawozdań finansowych ani cennika składek - wysokość składki widoczna jest dopiero w deklaracji członkowskiej',
    replace:
      'Izba nie publikuje sprawozdań finansowych, ale cennik składek jest jawny - stawki podaje wprost formularz członkowski, a reguły ich ustalania i egzekwowania statut',
    reason: 'Formularz członkowski (źródło 35) podaje stawki wprost.',
  },
  {
    pageId: 'model',
    find: 'To sytuacja typowa dla sprzedaży relacyjnej i negocjowanej indywidualnie, ale oznacza, że kandydat wchodzi do procesu bez znajomości poziomów cenowych.',
    replace:
      'Niejawne pozostają wyłącznie warunki partnerstw korporacyjnych, ustalane indywidualnie.',
    reason: 'Poziomy cenowe członkostwa są znane (źródło 35).',
  },
  {
    pageId: 'model',
    find: '<li>Wysokość składki nie jest publiczna - widoczna dopiero w deklaracji członkowskiej',
    replace:
      '<li>Wysokość składki jest jawna: 150 EUR (BASIC), 500 EUR (PRO) i 1 500 EUR (PREMIUM) rocznie, plus 20 EUR opłaty rejestracyjnej - szczegóły w sekcji „Cennik składek” powyżej',
    reason: 'Luka zamknięta przez formularz członkowski (źródło 35).',
  },
  {
    pageId: 'model',
    find: '. <span class="v">luka M1</span></li>',
    replace: '. <span class="v">150 / 500 / 1 500 EUR</span></li>',
    reason: 'Znacznik luki przy stawkach sk\u0142adek przesta\u0142 obowi\u0105zywa\u0107 (\u017ar\u00f3d\u0142o 35).',
  },
  {
    pageId: 'model',
    find: '<thead><tr><th>Pakiet</th><th>Wielkość firmy</th><th>Deklarowany zakres</th></tr></thead>',
    replace:
      '<thead><tr><th>Pakiet</th><th>Wielkość firmy</th><th>Składka roczna</th><th>Deklarowany zakres</th></tr></thead>',
    reason: 'Tabela pakietów zyskuje kolumnę cenową (źródło 35).',
  },
  {
    pageId: 'model',
    find: '<tr><td>BASIC</td><td>do 5 pracowników</td><td>',
    replace: '<tr><td>BASIC</td><td>do 5 pracowników</td><td class="num tabnum">150 EUR</td><td>',
    reason: 'Stawka z formularza członkowskiego (źródło 35).',
  },
  {
    pageId: 'model',
    find: '<tr><td>PRO</td><td>6-50 pracowników</td><td>',
    replace: '<tr><td>PRO</td><td>6-50 pracowników</td><td class="num tabnum">500 EUR</td><td>',
    reason: 'Stawka z formularza członkowskiego (źródło 35).',
  },
  {
    pageId: 'model',
    find: '<tr><td>PREMIUM</td><td>51-250 pracowników</td><td>',
    replace:
      '<tr><td>PREMIUM</td><td>51-250 pracowników</td><td class="num tabnum">1 500 EUR</td><td>',
    reason: 'Stawka z formularza członkowskiego (źródło 35).',
  },
  {
    pageId: 'model',
    find: '<tr><td>Corporate Partnership</td><td>powyżej 250 pracowników</td><td>',
    replace:
      '<tr><td>Corporate Partnership</td><td>powyżej 250 pracowników</td><td><span class="pill warn">indywidualnie</span></td><td>',
    reason: 'Kolumna cenowa wymaga wartości także w wierszu partnerstw.',
  },
  {
    pageId: 'model',
    find: '<tr><td>Składki członkowskie MŚP</td><td>powtarzalny, subskrypcyjny, trzy poziomy</td><td><span class="pill warn">ceny niejawne</span></td></tr>',
    replace:
      '<tr><td>Składki członkowskie MŚP</td><td>powtarzalny, subskrypcyjny, trzy poziomy</td><td><span class="pill pos">cennik jawny</span></td></tr>',
    reason: 'Stawki członkowskie są jawne (źródło 35); niejawna pozostaje struktura bazy.',
  },
  {
    pageId: 'model',
    find: '<p class="note">Konsekwencja dla roli: automatyczne odnowienie przesuwa ciężar retencji na czwarty kwartał - to naturalny moment kampanii utrzymaniowej i rozmów o wyższy pakiet.</p>',
    replace:
      '<p class="note">Konsekwencja dla roli: termin wypowiedzenia 31 grudnia kumuluje ryzyko rezygnacji w czwartym kwartale, ale statut wiąże płatność z rocznicą przystąpienia, więc fakturowanie rozkłada się na cały rok. Kampania utrzymaniowa idzie zatem kalendarzem grudniowym, a przepływy - kalendarzem rocznic.</p>',
    reason: 'Statut art. 22 ust. 2 (źródło 36) wiąże płatność z rocznicą, nie z rokiem kalendarzowym.',
  },
  {
    pageId: 'model',
    find: '<p class="note">Nie ustalono: przychodów izby, wysokości składek, liczby partnerów korporacyjnych ani dynamiki bazy członkowskiej miesiąc do miesiąca.',
    replace:
      '<p class="note">Nie ustalono: przychodów izby, struktury bazy w podziale na pakiety, liczby partnerów korporacyjnych ani dynamiki bazy członkowskiej miesiąc do miesiąca. Wysokość składek jest już znana i opisana powyżej.',
    reason: 'Wysokość składek przestała być luką (źródło 35).',
  },

  /* --- the same assumption echoed on other pages --- */
  {
    pageId: 'przeglad',
    find: 'Jednocześnie nie ma publicznego cennika składek',
    replace: 'Jednocześnie nie ma publicznych warunków partnerstw korporacyjnych',
    reason: 'Cennik składek jest jawny (źródło 35); niejawne pozostają partnerstwa.',
  },
  {
    pageId: 'struktura',
    find: '<p class="note">Nie ustalono: publicznych sprawozdań finansowych izby, wysokości składek ani relacji finansowych między izbą a Fundacją AI CEE. Te trzy luki warto zaadresować pytaniami na rozmowie (zakładka 12).',
    replace:
      '<p class="note">Nie ustalono: publicznych sprawozdań finansowych izby ani relacji finansowych między izbą a Fundacją AI CEE. Wysokość składek jest znana - szczegóły w zakładce 04. Pozostałe dwie luki warto zaadresować pytaniami na rozmowie (zakładka 12).',
    reason: 'Wysokość składek przestała być luką (źródło 35).',
  },
  {
    pageId: 'obszary',
    find: 'Trzy pakiety dla firm do 250 pracowników, ceny niejawne, odnowienie automatyczne z terminem wypowiedzenia 31 grudnia.',
    replace:
      'Trzy pakiety dla firm do 250 pracowników w cenach 150, 500 i 1 500 EUR rocznie, odnowienie automatyczne z terminem wypowiedzenia 31 grudnia.',
    reason: 'Stawki znane (źródło 35).',
  },
  {
    pageId: 'obszary',
    find: '<li>Wysokość składki widoczna dopiero w deklaracji członkowskiej - brak publicznego cennika',
    replace:
      '<li>Składki roczne: 150 EUR (BASIC), 500 EUR (PRO), 1 500 EUR (PREMIUM), plus jednorazowe 20 EUR opłaty rejestracyjnej',
    reason: 'Stawki znane (źródło 35).',
  },
  {
    pageId: 'oferta',
    find: '<li>Brak publicznego cennika i ustandaryzowanego procesu',
    replace: '<li>Brak ustandaryzowanego procesu sprzedaży przy jawnym już cenniku',
    reason: 'Cennik jest jawny (źródło 35); teza o procesie pozostaje aktualna.',
  },
  {
    pageId: 'rozmowa',
    find: '<li>Rozumiem też jego specyfikę: odnowienie jest automatyczne, jeśli nie ma wypowiedzenia do 31 grudnia, co czyni czwarty kwartał najważniejszym momentem roku dla retencji.',
    replace:
      '<li>Rozumiem też jego specyfikę: odnowienie jest automatyczne, jeśli nie ma wypowiedzenia do 31 grudnia, co czyni czwarty kwartał najważniejszym momentem roku dla retencji - przy czym statut wiąże samą płatność z rocznicą przystąpienia, więc przepływy idą innym kalendarzem niż rezygnacje.',
    reason: 'Doprecyzowanie statutem art. 22 ust. 2 (źródło 36).',
  },

  {
    pageId: 'organizacja',
    find: '<tr><td>Corporate Partnerships</td><td>agnieszka.gosztyla@aichamber.eu',
    replace:
      '<tr><td>Corporate Partnerships</td><td>members@aichamber.eu (wcze\u015bniej adres imienny Agnieszki Goszty\u0142y)',
    reason: 'Strona izby podaje dzi\u015b adres zbiorczy members@aichamber.eu.',
  },

  {
    pageId: 'rynek',
    find: 'po czwarte, brak publicznego cennika, kt\u00f3ry wyd\u0142u\u017ca cykl sprzeda\u017cy i utrudnia skalowanie procesu',
    replace:
      'po czwarte, brak ustandaryzowanego procesu sprzeda\u017cy, kt\u00f3ry wyd\u0142u\u017ca cykl i utrudnia skalowanie',
    reason: 'Cennik jest jawny (\u017ar\u00f3d\u0142o 35); s\u0142abo\u015bci\u0105 pozostaje proces, nie brak cen.',
  },
  {
    pageId: 'plan',
    find: ', brak publicznego cennika',
    replace: ', nieznana struktura bazy w podziale na pakiety',
    count: 2,
    reason: 'Cennik jest jawny (\u017ar\u00f3d\u0142o 35); nieznany pozosta\u0142 rozk\u0142ad pakiet\u00f3w.',
  },

  /* --- bibliography: two new primary sources --- */
  {
    pageId: 'zrodla',
    find: 'Trzydzieści cztery pozycje w zapisie chicagowskim, ponumerowane na stałe i pogrupowane według rodzaju źródła.',
    replace:
      'Czterdzieści trzy pozycje w zapisie chicagowskim, ponumerowanych na stałe i pogrupowanych według rodzaju źródła.',
    reason: 'Dopisane pozycje 35 i 36.',
  },
  {
    pageId: 'zrodla',
    find: ENTRY_34,
    replace: NEW_ENTRIES,
    reason: 'Nowe źródła pierwotne: formularz członkowski i statut.',
  },
  {
    pageId: 'zrodla',
    find: 'Wysokość składek członkowskich (BASIC, PRO, PREMIUM) oraz cen partnerstw korporacyjnych - widoczne dopiero w deklaracji członkowskiej.',
    replace:
      'Ceny partnerstw korporacyjnych - ustalane indywidualnie. Wysokość składek członkowskich jest już znana (150, 500 i 1 500 EUR rocznie, plus 20 EUR opłaty rejestracyjnej).',
    reason: 'Część luki zamknięta przez formularz członkowski (źródło 35).',
  },
];

/* ------------------------------------------------------------------ */

function patchHtml(html: string, patch: DossierPatch, hits: { n: number }): string {
  const count = html.split(patch.find).length - 1;
  if (count === 0) return html;
  hits.n += count;
  return html.split(patch.find).join(patch.replace);
}

function applyPatches(page: DossierPage): DossierPage {
  const patches = DOSSIER_PATCHES.filter((p) => p.pageId === page.id);
  if (patches.length === 0) return page;

  let lead = page.lead;
  const blocks = page.blocks.map((b) => ({ ...b }));

  for (const patch of patches) {
    const hits = { n: 0 };
    if (lead) lead = patchHtml(lead, patch, hits);
    for (const block of blocks) {
      if (block.kind === 'html') block.html = patchHtml(block.html, patch, hits);
      else if (block.kind === 'component' && block.caption)
        block.caption = patchHtml(block.caption, patch, hits);
      else if (block.kind === 'tabs')
        block.tabs = block.tabs.map((t) =>
          t.html == null ? t : { ...t, html: patchHtml(t.html, patch, hits) }
        );
    }
    const expected = patch.count ?? 1;
    if (hits.n !== expected) {
      const message =
        `Nieaktualna łatka dossier (${page.id}): oczekiwano ${expected} trafień, ` +
        `znaleziono ${hits.n} dla „${patch.find.slice(0, 60)}…”`;
      // A regenerated document that no longer contains the fragment must not
      // silently drop the correction.
      if (import.meta.env.DEV) throw new Error(message);
      console.warn(message);
    }
  }

  return { ...page, lead, blocks };
}

export function applyOverlays(pages: DossierPage[]): DossierPage[] {
  const patched = pages.map((page) => {
    const patched = applyPatches(page);
    const overlays = DOSSIER_OVERLAYS.filter((o) => o.pageId === patched.id);
    if (overlays.length === 0) return patched;
    const blocks = [...patched.blocks];
    // Splice from the back so earlier insertion points keep their indices.
    const ordered = [...overlays].sort(
      (a, b) => (b.at ?? blocks.length) - (a.at ?? blocks.length)
    );
    for (const overlay of ordered) blocks.splice(overlay.at ?? blocks.length, 0, ...overlay.blocks);
    return { ...patched, blocks };
  });
  // Hand-written pages that were never part of the source document.
  return [...patched, ...TRAFFIC_PAGES, ...SEO_PAGES];
}
