import type { DossierBlock, DossierPage } from './types';

/**
 * Hand-written additions layered on top of the generated pages.
 *
 * `01-*.ts` … `15-*.ts` and `index.ts` are regenerated by
 * `scripts/import-dossier.mjs` and lose anything edited into them. Content that
 * did not come from the source document therefore lives here — this file is
 * never touched by the importer.
 *
 * `at` is the index in the page's block list where the blocks are spliced in;
 * omit it to append at the end.
 */
export interface DossierOverlay {
  pageId: string;
  at?: number;
  blocks: DossierBlock[];
}

export const DOSSIER_OVERLAYS: DossierOverlay[] = [];

export function applyOverlays(pages: DossierPage[]): DossierPage[] {
  if (DOSSIER_OVERLAYS.length === 0) return pages;
  return pages.map((page) => {
    const overlays = DOSSIER_OVERLAYS.filter((o) => o.pageId === page.id);
    if (overlays.length === 0) return page;
    const blocks = [...page.blocks];
    // Splice from the back so earlier insertion points keep their indices.
    for (const overlay of [...overlays].sort((a, b) => (b.at ?? blocks.length) - (a.at ?? blocks.length))) {
      blocks.splice(overlay.at ?? blocks.length, 0, ...overlay.blocks);
    }
    return { ...page, blocks };
  });
}
