import { DOSSIER_PAGES } from './index';
import type { DossierPage } from './types';

/**
 * Which pages belong to the Rekrutacja view rather than to the dossier.
 *
 * This file exists as a separate module for the same reason `overlays.ts`
 * does: `01-*.ts` … `15-*.ts` and `index.ts` are regenerated by
 * `scripts/import-dossier.mjs` and lose anything edited into them. Splitting
 * the list here means a regeneration keeps working and the split survives it.
 *
 * The order is the order the tabs appear in, which is the order a candidate
 * reads them: who I am, what is on offer, how I fit, what I will be asked, and
 * the thirty seconds that has to land before any of it.
 */
export const RECRUITMENT_IDS = ['cv', 'oferta', 'fit', 'rozmowa', 'pitch'] as const;

export type RecruitmentTab = (typeof RECRUITMENT_IDS)[number];

const byId = (id: string) => DOSSIER_PAGES.find((p) => p.id === id);

/**
 * Fails loudly rather than silently rendering four tabs out of five: an id
 * that stops resolving means the importer renamed a page, and a missing tab is
 * exactly the kind of thing nobody notices in a diff.
 */
export const RECRUITMENT_PAGES: DossierPage[] = RECRUITMENT_IDS.map((id) => {
  const page = byId(id);
  if (!page) {
    throw new Error(
      `Strona rekrutacyjna „${id}” nie istnieje w DOSSIER_PAGES — sprawdź, czy importer nie zmienił identyfikatora.`
    );
  }
  return page;
});

const MOVED = new Set<string>(RECRUITMENT_IDS);

/** What is left in the dossier once the five pages have moved out. */
export const DOSSIER_REMAINING: DossierPage[] = DOSSIER_PAGES.filter((p) => !MOVED.has(p.id));

/** Regrouped after the split, so an emptied group does not leave a stray heading. */
export const DOSSIER_REMAINING_GROUPS: { group: string; pages: DossierPage[] }[] =
  DOSSIER_REMAINING.reduce(
    (acc, page) => {
      const last = acc[acc.length - 1];
      if (last && last.group === page.group) last.pages.push(page);
      else acc.push({ group: page.group, pages: [page] });
      return acc;
    },
    [] as { group: string; pages: DossierPage[] }[]
  );

/** The bibliography stays in the dossier; the recruitment view links into it. */
export const SOURCES_PAGE_ID = 'zrodla';
